// mobile/lib/services/app_localizations.dart

import 'dart:ui' as ui;

class AppLocale {
  /// Cihazın telefon dilini al (tr, en, de, ar, ru, fr, es, it, pt, nl, az, fa, ku, zh, ja, ko, hi, uk, pl, ro, bg, el)
  static String get currentLanguage {
    try {
      final code = ui.PlatformDispatcher.instance.locale.languageCode.toLowerCase();
      if (_localizedValues.containsKey(code)) {
        return code;
      }
    } catch (_) {}
    return 'tr'; // Varsayılan Türkçe
  }

  static bool get isTurkish => currentLanguage == 'tr';
  static bool get isEnglish => currentLanguage == 'en';
  static bool get isArabic => currentLanguage == 'ar';

  static final Map<String, Map<String, String>> _localizedValues = {
    // 🇹🇷 TÜRKÇE
    'tr': {
      'app_title': 'Hızlı ve Micro Sipariş',
      'login_subtitle': 'İşletme / Kullanıcı Giriş Paneli',
      'username': 'Kullanıcı Adı',
      'username_required': 'Kullanıcı adı giriniz',
      'password': 'Şifre',
      'password_required': 'Şifre giriniz',
      'login_btn': 'Giriş Yap',
      'super_admin_warn': 'Süper admin hesabı mobil uygulamadan açılamaz. Lütfen Web Panelini kullanın.',
      'login_failed': 'Giriş başarısız',
      'tab_menu': 'Menü',
      'tab_cart': 'Sepetim',
      'tab_account': 'Hesabım',
      'tab_orders': 'Siparişlerim',
      'tab_products': 'Ürünler',
      'tab_options': 'Seçenekler',
      'tab_categories': 'Kategoriler',
      'tab_customers': 'Müşteriler',
      'tab_announcements': 'Duyurular',
      'search_product': 'Ürün veya kategori ara...',
      'all_categories': 'Tümü',
      'add_to_cart': 'Sepete Ekle',
      'added_to_cart': 'Sepete eklendi',
      'out_of_stock': 'Tükendi',
      'cart_empty': 'Sepetiniz henüz boş.',
      'cart_title': 'Sepetim',
      'clear_cart': 'Sepeti Temizle',
      'order_note': 'Sipariş Notu (Örn: Acılı olsun, vb.)',
      'total': 'Toplam',
      'total_amount': 'Toplam Tutar',
      'confirm_order': 'Siparişi Onayla',
      'order_received': 'Siparişiniz başarıyla alındı!',
      'order_note_label': 'Not',
      'options_label': 'Seçenekler',
      'select_options': 'Seçenekleri Belirleyin',
      'continue_btn': 'Devam Et',
      'cancel_btn': 'Vazgeç',
      'close_btn': 'Kapat',
      'save_btn': 'Kaydet',
      'update_btn': 'Güncelle',
      'delete_btn': 'Sil',
      'yes_delete': 'Evet, Sil',
      'account_summary': 'Hesap Özeti',
      'unpaid_balance': 'Açık Hesap (Borç)',
      'total_paid': 'Toplam Ödenen',
      'period': 'Dönem',
      'period_all': 'Tümü',
      'period_daily': 'Bugün (Günlük)',
      'period_weekly': 'Bu Hafta (7 Gün)',
      'period_monthly': 'Bu Ay (30 Gün)',
      'payment_status': 'Ödeme',
      'pay_all': 'Tümü',
      'pay_unpaid': '⏳ Ödenmemişler (Açık)',
      'pay_paid': '✅ Ödenenler (Geçmiş)',
      'pay_cancelled': '❌ İptal Edilenler',
      'status_paid': 'ÖDENDİ',
      'status_unpaid': 'ÖDENMEDİ',
      'no_account_records': 'Hesabınıza ait sipariş kaydı bulunmuyor.',
      'no_filtered_records': 'Seçilen filtreye ait kayıt bulunamadı.',
      'order_number': 'Sipariş',
      'date': 'Tarih',
      'close_account_btn': 'Hesabı Kapat',
      'all_orders_closed': 'Tüm bekleyen siparişler ödendi olarak kapatıldı.',
      'status_pending': 'Bekliyor',
      'status_accepted': 'Onaylandı',
      'status_preparing': 'Hazırlanıyor',
      'status_delivered': 'Teslim Edildi',
      'status_cancelled': 'İptal',
      'status_approved': 'Onayla',
      'status_cancel': 'İptal Et',
      'shop_open': 'AÇIK',
      'shop_closed': 'KAPALI',
      'shop_open_tip': 'Dükkan Açık (Kapatmak için tıkla)',
      'shop_closed_tip': 'Dükkan Kapalı (Açmak için tıkla)',
      'work_hours': 'Mesai Saatleri',
      'opening_time': 'Açılış Saati',
      'closing_time': 'Kapanış Saati',
      'auto_hours': 'Otomatik Mesai Saatleri Aktif',
      'shop_closed_note': 'Kapanış Notu / Müşteri Bilgilendirmesi',
      'shop_closed_note_hint': 'Örn: Tadilat nedeniyle kapalıyız.',
      'shop_panel': 'Dükkan Paneli',
      'shop_owner_label': 'Dükkan Sahibi',
      'customer_panel': 'Müşteri Sipariş Ekranı',
      'logout': 'Çıkış',
      'refresh': 'Yenile',
      'add_product': 'Ürün Ekle',
      'edit_product': 'Ürün Düzenle',
      'product_name': 'Ürün Adı',
      'product_price': 'Fiyat (TL)',
      'product_desc': 'Açıklama',
      'product_img': 'Görsel Linki / URL',
      'gallery_btn': 'Galeri',
      'add_option': 'Seçenek Ekle',
      'manage_options': 'Ürün Seçenekleri Yönetimi',
      'add_category': 'Kategori Ekle',
      'edit_category': 'Kategori Düzenle',
      'category_name': 'Kategori Adı',
      'add_customer': 'Müşteri Ekle',
      'edit_customer': 'Müşteriyi Düzenle',
      'customer_name': 'Müşteri Ad Soyad (Ofis/Masa No)',
      'customer_phone': 'Telefon Numarası',
      'customer_orders_history': 'Hesap & Sipariş Geçmişi',
      'announcement_title': 'Duyuru Başlığı',
      'announcement_content': 'Duyuru Metni',
      'add_announcement': 'Duyuru Yayınla',
      'no_orders': 'Henüz sipariş yok.',
      'no_products': 'Henüz ürün yok.',
      'no_categories': 'Henüz kategori yok.',
      'no_customers': 'Kayıtlı müşteri yok.',
      'no_announcements': 'Yayınlanmış duyuru yok.',
    },

    // 🇬🇧 İNGİLİZCE (EN)
    'en': {
      'app_title': 'Quick & Micro Order',
      'login_subtitle': 'Business / Customer Login Portal',
      'username': 'Username',
      'username_required': 'Please enter username',
      'password': 'Password',
      'password_required': 'Please enter password',
      'login_btn': 'Sign In',
      'super_admin_warn': 'Super admin cannot log in via mobile. Please use the Web Panel.',
      'login_failed': 'Login failed',
      'tab_menu': 'Menu',
      'tab_cart': 'Cart',
      'tab_account': 'My Account',
      'tab_orders': 'My Orders',
      'tab_products': 'Products',
      'tab_options': 'Options',
      'tab_categories': 'Categories',
      'tab_customers': 'Customers',
      'tab_announcements': 'Notices',
      'search_product': 'Search product or category...',
      'all_categories': 'All',
      'add_to_cart': 'Add to Cart',
      'added_to_cart': 'Added to cart',
      'out_of_stock': 'Out of Stock',
      'cart_empty': 'Your cart is empty.',
      'cart_title': 'My Cart',
      'clear_cart': 'Clear Cart',
      'order_note': 'Order Note (e.g., extra sauce)',
      'total': 'Total',
      'total_amount': 'Total Amount',
      'confirm_order': 'Confirm Order',
      'order_received': 'Your order has been received!',
      'order_note_label': 'Note',
      'options_label': 'Options',
      'select_options': 'Choose Options',
      'continue_btn': 'Continue',
      'cancel_btn': 'Cancel',
      'close_btn': 'Close',
      'save_btn': 'Save',
      'update_btn': 'Update',
      'delete_btn': 'Delete',
      'yes_delete': 'Yes, Delete',
      'account_summary': 'Account Summary',
      'unpaid_balance': 'Open Balance (Debt)',
      'total_paid': 'Total Paid',
      'period': 'Period',
      'period_all': 'All Time',
      'period_daily': 'Today (Daily)',
      'period_weekly': 'This Week (7 Days)',
      'period_monthly': 'This Month (30 Days)',
      'payment_status': 'Payment',
      'pay_all': 'All',
      'pay_unpaid': '⏳ Unpaid (Open)',
      'pay_paid': '✅ Paid (Past)',
      'pay_cancelled': '❌ Cancelled',
      'status_paid': 'PAID',
      'status_unpaid': 'UNPAID',
      'no_account_records': 'No account records found.',
      'no_filtered_records': 'No records match the selected filter.',
      'order_number': 'Order',
      'date': 'Date',
      'close_account_btn': 'Settle Account',
      'all_orders_closed': 'All pending orders marked as paid.',
      'status_pending': 'Pending',
      'status_accepted': 'Accepted',
      'status_preparing': 'Preparing',
      'status_delivered': 'Delivered',
      'status_cancelled': 'Cancelled',
      'status_approved': 'Accept',
      'status_cancel': 'Cancel Order',
      'shop_open': 'OPEN',
      'shop_closed': 'CLOSED',
      'shop_open_tip': 'Shop is Open (Click to close)',
      'shop_closed_tip': 'Shop is Closed (Click to open)',
      'work_hours': 'Operating Hours',
      'opening_time': 'Opening Time',
      'closing_time': 'Closing Time',
      'auto_hours': 'Enable Auto Hours',
      'shop_closed_note': 'Closure Notice / Customer Info',
      'shop_closed_note_hint': 'e.g., Closed for renovation.',
      'shop_panel': 'Shop Dashboard',
      'shop_owner_label': 'Shop Owner',
      'customer_panel': 'Customer Order Screen',
      'logout': 'Log Out',
      'refresh': 'Refresh',
      'add_product': 'Add Product',
      'edit_product': 'Edit Product',
      'product_name': 'Product Name',
      'product_price': 'Price',
      'product_desc': 'Description',
      'product_img': 'Image URL',
      'gallery_btn': 'Gallery',
      'add_option': 'Add Option',
      'manage_options': 'Product Options Management',
      'add_category': 'Add Category',
      'edit_category': 'Edit Category',
      'category_name': 'Category Name',
      'add_customer': 'Add Customer',
      'edit_customer': 'Edit Customer',
      'customer_name': 'Customer Full Name (Office/Desk)',
      'customer_phone': 'Phone Number',
      'customer_orders_history': 'Account & Order History',
      'announcement_title': 'Notice Title',
      'announcement_content': 'Notice Content',
      'add_announcement': 'Post Notice',
      'no_orders': 'No orders yet.',
      'no_products': 'No products yet.',
      'no_categories': 'No categories yet.',
      'no_customers': 'No customers registered.',
      'no_announcements': 'No notices posted.',
    },

    // 🇩🇪 ALMANCA (DE)
    'de': {
      'app_title': 'Schnell- & Mikrobestsystem',
      'login_subtitle': 'Betrieb / Kunden Login Portal',
      'username': 'Benutzername',
      'username_required': 'Bitte Benutzernamen eingeben',
      'password': 'Passwort',
      'password_required': 'Bitte Passwort eingeben',
      'login_btn': 'Anmelden',
      'super_admin_warn': 'Super-Admin kann sich nicht mobil anmelden.',
      'login_failed': 'Anmeldung fehlgeschlagen',
      'tab_menu': 'Menü',
      'tab_cart': 'Warenkorb',
      'tab_account': 'Mein Konto',
      'tab_orders': 'Bestellungen',
      'tab_products': 'Produkte',
      'tab_options': 'Optionen',
      'tab_categories': 'Kategorien',
      'tab_customers': 'Kunden',
      'tab_announcements': 'Mitteilungen',
      'search_product': 'Produkt suchen...',
      'all_categories': 'Alle',
      'add_to_cart': 'In den Warenkorb',
      'added_to_cart': 'Hinzugefügt',
      'out_of_stock': 'Ausverkauft',
      'cart_empty': 'Ihr Warenkorb ist leer.',
      'cart_title': 'Warenkorb',
      'clear_cart': 'Warenkorb leeren',
      'order_note': 'Bestellnotiz',
      'total': 'Gesamt',
      'total_amount': 'Gesamtbetrag',
      'confirm_order': 'Bestellung aufgeben',
      'order_received': 'Bestellung erfolgreich eingegangen!',
      'order_note_label': 'Notiz',
      'options_label': 'Optionen',
      'select_options': 'Optionen wählen',
      'continue_btn': 'Weiter',
      'cancel_btn': 'Abbrechen',
      'close_btn': 'Schließen',
      'save_btn': 'Speichern',
      'update_btn': 'Aktualisieren',
      'delete_btn': 'Löschen',
      'yes_delete': 'Ja, Löschen',
      'account_summary': 'Kontoübersicht',
      'unpaid_balance': 'Offener Betrag (Schulden)',
      'total_paid': 'Gesamt Bezahlt',
      'period': 'Zeitraum',
      'period_all': 'Alle',
      'period_daily': 'Heute (Täglich)',
      'period_weekly': 'Diese Woche (7 Tage)',
      'period_monthly': 'Diesen Monat (30 Tage)',
      'payment_status': 'Zahlung',
      'pay_all': 'Alle',
      'pay_unpaid': '⏳ Unbezahlt (Offen)',
      'pay_paid': '✅ Bezahlt (Historie)',
      'pay_cancelled': '❌ Storniert',
      'status_paid': 'BEZAHLT',
      'status_unpaid': 'OFFEN',
      'no_account_records': 'Keine Kontoeinträge gefunden.',
      'no_filtered_records': 'Keine Einträge für den Filter.',
      'order_number': 'Bestellung',
      'date': 'Datum',
      'close_account_btn': 'Konto ausgleichen',
      'all_orders_closed': 'Alle offenen Bestellungen als bezahlt markiert.',
      'status_pending': 'Wartend',
      'status_accepted': 'Akzeptiert',
      'status_preparing': 'Wird zubereitet',
      'status_delivered': 'Geliefert',
      'status_cancelled': 'Storniert',
      'status_approved': 'Bestätigen',
      'status_cancel': 'Stornieren',
      'shop_open': 'GEÖFFNET',
      'shop_closed': 'GESCHLOSSEN',
      'shop_open_tip': 'Laden geöffnet',
      'shop_closed_tip': 'Laden geschlossen',
      'work_hours': 'Öffnungszeiten',
      'opening_time': 'Öffnung',
      'closing_time': 'Schließung',
      'auto_hours': 'Automatische Öffnungszeiten',
      'shop_closed_note': 'Schließungsgrund',
      'shop_closed_note_hint': 'z.B. Wegen Renovierung geschlossen.',
      'shop_panel': 'Laden-Dashboard',
      'shop_owner_label': 'Inhaber',
      'customer_panel': 'Kunden-Bestellansicht',
      'logout': 'Abmelden',
      'refresh': 'Aktualisieren',
      'add_product': 'Produkt hinzufügen',
      'edit_product': 'Produkt bearbeiten',
      'product_name': 'Produktname',
      'product_price': 'Preis',
      'product_desc': 'Beschreibung',
      'product_img': 'Bild-URL',
      'gallery_btn': 'Galerie',
      'add_option': 'Option hinzufügen',
      'manage_options': 'Optionen verwalten',
      'add_category': 'Kategorie hinzufügen',
      'edit_category': 'Kategorie bearbeiten',
      'category_name': 'Kategoriename',
      'add_customer': 'Kunde hinzufügen',
      'edit_customer': 'Kunde bearbeiten',
      'customer_name': 'Kundenname (Büro/Tisch)',
      'customer_phone': 'Telefonnummer',
      'customer_orders_history': 'Konto- & Bestellhistorie',
      'announcement_title': 'Titel der Mitteilung',
      'announcement_content': 'Inhalt der Mitteilung',
      'add_announcement': 'Mitteilung veröffentlichen',
      'no_orders': 'Noch keine Bestellungen.',
      'no_products': 'Noch keine Produkte.',
      'no_categories': 'Noch keine Kategorien.',
      'no_customers': 'Keine Kunden registriert.',
      'no_announcements': 'Keine Mitteilungen vorhanden.',
    },

    // 🇸🇦 ARAPÇA (AR)
    'ar': {
      'app_title': 'نظام الطلب السريع',
      'login_subtitle': 'لوحة دخول المتجر / العميل',
      'username': 'اسم المستخدم',
      'username_required': 'يرجى إدخال اسم المستخدم',
      'password': 'كلمة المرور',
      'password_required': 'يرجى إدخال كلمة المرور',
      'login_btn': 'تسجيل الدخول',
      'super_admin_warn': 'لا يمكن تسجيل دخول المشرف العام عبر التطبيق.',
      'login_failed': 'فشل تسجيل الدخول',
      'tab_menu': 'القائمة',
      'tab_cart': 'سلتي',
      'tab_account': 'حسابي',
      'tab_orders': 'طلباتي',
      'tab_products': 'المنتجات',
      'tab_options': 'الخيارات',
      'tab_categories': 'الأقسام',
      'tab_customers': 'الزبائن',
      'tab_announcements': 'الإعلانات',
      'search_product': 'البحث عن منتج...',
      'all_categories': 'الكل',
      'add_to_cart': 'إضافة إلى السلة',
      'added_to_cart': 'تمت الإضافة للسلة',
      'out_of_stock': 'نفدت الكمية',
      'cart_empty': 'سلة التسوق فارغة.',
      'cart_title': 'سلة التسوق',
      'clear_cart': 'إفراغ السلة',
      'order_note': 'ملاحظة الطلب',
      'total': 'المجموع',
      'total_amount': 'المجموع الكلي',
      'confirm_order': 'تأكيد الطلب',
      'order_received': 'تم استلام طلبك بنجاح!',
      'order_note_label': 'ملاحظة',
      'options_label': 'الخيارات',
      'select_options': 'حدد الخيارات',
      'continue_btn': 'متابعة',
      'cancel_btn': 'إلغاء',
      'close_btn': 'إغلاق',
      'save_btn': 'حفظ',
      'update_btn': 'تحديث',
      'delete_btn': 'حذف',
      'yes_delete': 'نعم، احذف',
      'account_summary': 'ملخص الحساب',
      'unpaid_balance': 'الحساب المفتوح (الديون)',
      'total_paid': 'المبلغ المدفوع',
      'period': 'الفترة',
      'period_all': 'الكل',
      'period_daily': 'اليوم (يومي)',
      'period_weekly': 'هذا الأسبوع (7 أيام)',
      'period_monthly': 'هذا الشهر (30 يوماً)',
      'payment_status': 'الدفع',
      'pay_all': 'الكل',
      'pay_unpaid': '⏳ غير مدفوع (مفتوح)',
      'pay_paid': '✅ مدفوع (سابق)',
      'pay_cancelled': '❌ ملغي',
      'status_paid': 'مدفوع',
      'status_unpaid': 'غير مدفوع',
      'no_account_records': 'لا توجد سجلات حساب.',
      'no_filtered_records': 'لا توجد نتائج للتصفية المحددة.',
      'order_number': 'طلب',
      'date': 'التاريخ',
      'close_account_btn': 'إغلاق الحساب',
      'all_orders_closed': 'تم تعيين جميع الطلبات المعلقة كمدفوعة.',
      'status_pending': 'قيد الانتظار',
      'status_accepted': 'تم القبول',
      'status_preparing': 'قيد التحضير',
      'status_delivered': 'تم التسليم',
      'status_cancelled': 'ملغي',
      'status_approved': 'قبول',
      'status_cancel': 'إلغاء الطلب',
      'shop_open': 'مفتوح',
      'shop_closed': 'مغلق',
      'shop_open_tip': 'المتجر مفتوح',
      'shop_closed_tip': 'المتجر مغلق',
      'work_hours': 'ساعات العمل',
      'opening_time': 'وقت الافتتاح',
      'closing_time': 'وقت الإغلاق',
      'auto_hours': 'تفعيل ساعات العمل التلقائية',
      'shop_closed_note': 'سبب الإغلاق',
      'shop_closed_note_hint': 'مثال: مغلق لأعمال الصيانة.',
      'shop_panel': 'لوحة المتجر',
      'shop_owner_label': 'صاحب المتجر',
      'customer_panel': 'شاشة طلبات الزبائن',
      'logout': 'تسجيل الخروج',
      'refresh': 'تحديث',
      'add_product': 'إضافة منتج',
      'edit_product': 'تعديل منتج',
      'product_name': 'اسم المنتج',
      'product_price': 'السعر',
      'product_desc': 'الوصف',
      'product_img': 'رابط الصورة',
      'gallery_btn': 'المعرض',
      'add_option': 'إضافة خيار',
      'manage_options': 'إدارة خيارات المنتجات',
      'add_category': 'إضافة قسم',
      'edit_category': 'تعديل القسم',
      'category_name': 'اسم القسم',
      'add_customer': 'إضافة زبون',
      'edit_customer': 'تعديل بيانات الزبون',
      'customer_name': 'اسم الزبون (المكتب/الطاولة)',
      'customer_phone': 'رقم الهاتف',
      'customer_orders_history': 'سجل الحساب والطلبات',
      'announcement_title': 'عنوان الإعلان',
      'announcement_content': 'نص الإعلان',
      'add_announcement': 'نشر إعلان',
      'no_orders': 'لا توجد طلبات بعد.',
      'no_products': 'لا توجد منتجات بعد.',
      'no_categories': 'لا توجد أقسام بعد.',
      'no_customers': 'لا يوجد زبائن مسجلون.',
      'no_announcements': 'لا توجد إعلانات منشورة.',
    },

    // 🇷🇺 RUSÇA (RU)
    'ru': {
      'app_title': 'Быстрый и Микро Заказ',
      'login_subtitle': 'Панель Входа Бизнес / Клиент',
      'username': 'Имя пользователя',
      'username_required': 'Введите имя пользователя',
      'password': 'Пароль',
      'password_required': 'Введите пароль',
      'login_btn': 'Войти',
      'super_admin_warn': 'Супер-администратор не может войти через приложение.',
      'login_failed': 'Ошибка входа',
      'tab_menu': 'Меню',
      'tab_cart': 'Корзина',
      'tab_account': 'Мой счет',
      'tab_orders': 'Мои заказы',
      'tab_products': 'Товары',
      'tab_options': 'Опции',
      'tab_categories': 'Категории',
      'tab_customers': 'Клиенты',
      'tab_announcements': 'Объявления',
      'search_product': 'Поиск товара...',
      'all_categories': 'Все',
      'add_to_cart': 'В корзину',
      'added_to_cart': 'Добавлено в корзину',
      'out_of_stock': 'Нет в наличии',
      'cart_empty': 'Ваша корзина пуста.',
      'cart_title': 'Корзина',
      'clear_cart': 'Очистить корзину',
      'order_note': 'Примечание к заказу',
      'total': 'Итого',
      'total_amount': 'Общая сумма',
      'confirm_order': 'Подтвердить заказ',
      'order_received': 'Ваш заказ успешно принят!',
      'order_note_label': 'Примечание',
      'options_label': 'Опции',
      'select_options': 'Выберите опции',
      'continue_btn': 'Продолжить',
      'cancel_btn': 'Отмена',
      'close_btn': 'Закрыть',
      'save_btn': 'Сохранить',
      'update_btn': 'Обновить',
      'delete_btn': 'Удалить',
      'yes_delete': 'Да, удалить',
      'account_summary': 'Сводка по счету',
      'unpaid_balance': 'Открытый счет (Долг)',
      'total_paid': 'Всего оплачено',
      'period': 'Период',
      'period_all': 'Все время',
      'period_daily': 'Сегодня (День)',
      'period_weekly': 'Эта неделя (7 дней)',
      'period_monthly': 'Этот месяц (30 дней)',
      'payment_status': 'Оплата',
      'pay_all': 'Все',
      'pay_unpaid': '⏳ Не оплачено (Открыто)',
      'pay_paid': '✅ Оплачено (История)',
      'pay_cancelled': '❌ Отменено',
      'status_paid': 'ОПЛАЧЕНО',
      'status_unpaid': 'НЕ ОПЛАЧЕНО',
      'no_account_records': 'Записи по счету не найдены.',
      'no_filtered_records': 'Нет записей по выбранному фильтру.',
      'order_number': 'Заказ',
      'date': 'Дата',
      'close_account_btn': 'Закрыть счет',
      'all_orders_closed': 'Все ожидающие заказы отмечены как оплаченные.',
      'status_pending': 'В ожидании',
      'status_accepted': 'Принят',
      'status_preparing': 'Готовится',
      'status_delivered': 'Доставлен',
      'status_cancelled': 'Отменен',
      'status_approved': 'Подтвердить',
      'status_cancel': 'Отменить заказ',
      'shop_open': 'ОТКРЫТО',
      'shop_closed': 'ЗАКРЫТО',
      'shop_open_tip': 'Заведение открыто',
      'shop_closed_tip': 'Заведение закрыто',
      'work_hours': 'Часы работы',
      'opening_time': 'Время открытия',
      'closing_time': 'Время закрытия',
      'auto_hours': 'Автоматические часы работы',
      'shop_closed_note': 'Причина закрытия',
      'shop_closed_note_hint': 'напр. Закрыто на ремонт.',
      'shop_panel': 'Панель управления',
      'shop_owner_label': 'Владелец',
      'customer_panel': 'Экран заказов клиента',
      'logout': 'Выйти',
      'refresh': 'Обновить',
      'add_product': 'Добавить товар',
      'edit_product': 'Редактировать товар',
      'product_name': 'Название товара',
      'product_price': 'Цена',
      'product_desc': 'Описание',
      'product_img': 'Ссылка на фото',
      'gallery_btn': 'Галерея',
      'add_option': 'Добавить опцию',
      'manage_options': 'Управление опциями',
      'add_category': 'Добавить категорию',
      'edit_category': 'Редактировать категорию',
      'category_name': 'Название категории',
      'add_customer': 'Добавить клиента',
      'edit_customer': 'Редактировать клиента',
      'customer_name': 'ФИО клиента (Офис/Стол)',
      'customer_phone': 'Номер телефона',
      'customer_orders_history': 'История счета и заказов',
      'announcement_title': 'Заголовок объявления',
      'announcement_content': 'Текст объявления',
      'add_announcement': 'Опубликовать объявление',
      'no_orders': 'Заказов пока нет.',
      'no_products': 'Товаров пока нет.',
      'no_categories': 'Категорий пока нет.',
      'no_customers': 'Клиенты не зарегистрированы.',
      'no_announcements': 'Нет объявлений.',
    },

    // 🇫🇷 FRANSIZCA (FR)
    'fr': {
      'app_title': 'Commande Rapide & Micro',
      'login_subtitle': 'Portail de Connexion Entreprise / Client',
      'username': 'Nom d\'utilisateur',
      'username_required': 'Veuillez entrer un nom d\'utilisateur',
      'password': 'Mot de passe',
      'password_required': 'Veuillez entrer un mot de passe',
      'login_btn': 'Se connecter',
      'super_admin_warn': 'Le super admin ne peut pas se connecter sur mobile.',
      'login_failed': 'Échec de connexion',
      'tab_menu': 'Menu',
      'tab_cart': 'Panier',
      'tab_account': 'Mon Compte',
      'tab_orders': 'Mes Commandes',
      'tab_products': 'Produits',
      'tab_options': 'Options',
      'tab_categories': 'Catégories',
      'tab_customers': 'Clients',
      'tab_announcements': 'Annonces',
      'search_product': 'Rechercher un produit...',
      'all_categories': 'Tout',
      'add_to_cart': 'Ajouter au panier',
      'added_to_cart': 'Ajouté au panier',
      'out_of_stock': 'Épuisé',
      'cart_empty': 'Votre panier est vide.',
      'cart_title': 'Mon Panier',
      'clear_cart': 'Vider le panier',
      'order_note': 'Note de commande',
      'total': 'Total',
      'total_amount': 'Montant Total',
      'confirm_order': 'Confirmer la commande',
      'order_received': 'Votre commande a été reçue !',
      'order_note_label': 'Note',
      'options_label': 'Options',
      'select_options': 'Choisir les options',
      'continue_btn': 'Continuer',
      'cancel_btn': 'Annuler',
      'close_btn': 'Fermer',
      'save_btn': 'Enregistrer',
      'update_btn': 'Mettre à jour',
      'delete_btn': 'Supprimer',
      'yes_delete': 'Oui, Supprimer',
      'account_summary': 'Résumé du Compte',
      'unpaid_balance': 'Compte Ouvert (Dette)',
      'total_paid': 'Total Payé',
      'period': 'Période',
      'period_all': 'Tout',
      'period_daily': 'Aujourd\'hui (Quotidien)',
      'period_weekly': 'Cette Semaine (7 Jours)',
      'period_monthly': 'Ce Mois (30 Jours)',
      'payment_status': 'Paiement',
      'pay_all': 'Tout',
      'pay_unpaid': '⏳ Non Payé (Ouvert)',
      'pay_paid': '✅ Payé (Historique)',
      'pay_cancelled': '❌ Annulé',
      'status_paid': 'PAYÉ',
      'status_unpaid': 'NON PAYÉ',
      'no_account_records': 'Aucun historique de compte trouvé.',
      'no_filtered_records': 'Aucun enregistrement pour ce filtre.',
      'order_number': 'Commande',
      'date': 'Date',
      'close_account_btn': 'Régler le compte',
      'all_orders_closed': 'Toutes les commandes en attente sont payées.',
      'status_pending': 'En attente',
      'status_accepted': 'Acceptée',
      'status_preparing': 'En préparation',
      'status_delivered': 'Livrée',
      'status_cancelled': 'Annulée',
      'status_approved': 'Accepter',
      'status_cancel': 'Annuler',
      'shop_open': 'OUVERT',
      'shop_closed': 'FERMÉ',
      'shop_open_tip': 'Boutique ouverte',
      'shop_closed_tip': 'Boutique fermée',
      'work_hours': 'Heures d\'ouverture',
      'opening_time': 'Heure d\'ouverture',
      'closing_time': 'Heure de fermeture',
      'auto_hours': 'Heures automatiques activées',
      'shop_closed_note': 'Motif de fermeture',
      'shop_closed_note_hint': 'ex: Fermé pour rénovation.',
      'shop_panel': 'Tableau de Bord',
      'shop_owner_label': 'Propriétaire',
      'customer_panel': 'Écran de commande client',
      'logout': 'Déconnexion',
      'refresh': 'Actualiser',
      'add_product': 'Ajouter un produit',
      'edit_product': 'Modifier le produit',
      'product_name': 'Nom du produit',
      'product_price': 'Prix',
      'product_desc': 'Description',
      'product_img': 'URL de l\'image',
      'gallery_btn': 'Galerie',
      'add_option': 'Ajouter une option',
      'manage_options': 'Gérer les options',
      'add_category': 'Ajouter une catégorie',
      'edit_category': 'Modifier la catégorie',
      'category_name': 'Nom de la catégorie',
      'add_customer': 'Ajouter un client',
      'edit_customer': 'Modifier le client',
      'customer_name': 'Nom du client (Bureau/Table)',
      'customer_phone': 'Numéro de téléphone',
      'customer_orders_history': 'Historique Compte & Commandes',
      'announcement_title': 'Titre de l\'annonce',
      'announcement_content': 'Contenu de l\'annonce',
      'add_announcement': 'Publier une annonce',
      'no_orders': 'Aucune commande.',
      'no_products': 'Aucun produit.',
      'no_categories': 'Aucune catégorie.',
      'no_customers': 'Aucun client enregistré.',
      'no_announcements': 'Aucune annonce.',
    },

    // 🇪🇸 İSPANYOLCA (ES)
    'es': {
      'app_title': 'Pedidos Rápidos y Micro',
      'login_subtitle': 'Panel de Inicio Negocio / Cliente',
      'username': 'Nombre de usuario',
      'username_required': 'Ingrese nombre de usuario',
      'password': 'Contraseña',
      'password_required': 'Ingrese contraseña',
      'login_btn': 'Iniciar Sesión',
      'super_admin_warn': 'Super admin no disponible en móvil.',
      'login_failed': 'Error al iniciar sesión',
      'tab_menu': 'Menú',
      'tab_cart': 'Mi Carrito',
      'tab_account': 'Mi Cuenta',
      'tab_orders': 'Mis Pedidos',
      'tab_products': 'Productos',
      'tab_options': 'Opciones',
      'tab_categories': 'Categorías',
      'tab_customers': 'Clientes',
      'tab_announcements': 'Avisos',
      'search_product': 'Buscar producto...',
      'all_categories': 'Todo',
      'add_to_cart': 'Añadir al Carrito',
      'added_to_cart': 'Añadido al carrito',
      'out_of_stock': 'Agotado',
      'cart_empty': 'Tu carrito está vacío.',
      'cart_title': 'Mi Carrito',
      'clear_cart': 'Vaciar Carrito',
      'order_note': 'Nota del pedido',
      'total': 'Total',
      'total_amount': 'Importe Total',
      'confirm_order': 'Confirmar Pedido',
      'order_received': '¡Pedido recibido con éxito!',
      'order_note_label': 'Nota',
      'options_label': 'Opciones',
      'select_options': 'Elegir opciones',
      'continue_btn': 'Continuar',
      'cancel_btn': 'Cancelar',
      'close_btn': 'Cerrar',
      'save_btn': 'Guardar',
      'update_btn': 'Actualizar',
      'delete_btn': 'Eliminar',
      'yes_delete': 'Sí, Eliminar',
      'account_summary': 'Resumen de Cuenta',
      'unpaid_balance': 'Cuenta Abierta (Deuda)',
      'total_paid': 'Total Pagado',
      'period': 'Período',
      'period_all': 'Todo',
      'period_daily': 'Hoy (Diario)',
      'period_weekly': 'Esta Semana (7 Días)',
      'period_monthly': 'Este Mes (30 Días)',
      'payment_status': 'Pago',
      'pay_all': 'Todo',
      'pay_unpaid': '⏳ Pendiente (Abierto)',
      'pay_paid': '✅ Pagado (Historial)',
      'pay_cancelled': '❌ Cancelado',
      'status_paid': 'PAGADO',
      'status_unpaid': 'PENDIENTE',
      'no_account_records': 'No hay registros de cuenta.',
      'no_filtered_records': 'No hay registros para este filtro.',
      'order_number': 'Pedido',
      'date': 'Fecha',
      'close_account_btn': 'Liquidar Cuenta',
      'all_orders_closed': 'Todos los pedidos pendientes marcados como pagados.',
      'status_pending': 'Pendiente',
      'status_accepted': 'Aceptado',
      'status_preparing': 'Preparando',
      'status_delivered': 'Entregado',
      'status_cancelled': 'Cancelado',
      'status_approved': 'Aceptar',
      'status_cancel': 'Cancelar Pedido',
      'shop_open': 'ABIERTO',
      'shop_closed': 'CERRADO',
      'shop_open_tip': 'Tienda abierta',
      'shop_closed_tip': 'Tienda cerrada',
      'work_hours': 'Horario de Trabajo',
      'opening_time': 'Apertura',
      'closing_time': 'Cierre',
      'auto_hours': 'Horario automático activo',
      'shop_closed_note': 'Nota de Cierre',
      'shop_closed_note_hint': 'Ej: Cerrado por reformas.',
      'shop_panel': 'Panel de Tienda',
      'shop_owner_label': 'Propietario',
      'customer_panel': 'Pantalla de Pedidos',
      'logout': 'Cerrar Sesión',
      'refresh': 'Actualizar',
      'add_product': 'Añadir Producto',
      'edit_product': 'Editar Producto',
      'product_name': 'Nombre del Producto',
      'product_price': 'Precio',
      'product_desc': 'Descripción',
      'product_img': 'URL de Imagen',
      'gallery_btn': 'Galería',
      'add_option': 'Añadir Opción',
      'manage_options': 'Gestionar Opciones',
      'add_category': 'Añadir Categoría',
      'edit_category': 'Editar Categoría',
      'category_name': 'Nombre de Categoría',
      'add_customer': 'Añadir Cliente',
      'edit_customer': 'Editar Cliente',
      'customer_name': 'Nombre del Cliente',
      'customer_phone': 'Teléfono',
      'customer_orders_history': 'Historial de Cuenta y Pedidos',
      'announcement_title': 'Título del Aviso',
      'announcement_content': 'Contenido del Aviso',
      'add_announcement': 'Publicar Aviso',
      'no_orders': 'No hay pedidos todavía.',
      'no_products': 'No hay productos todavía.',
      'no_categories': 'No hay categorías todavía.',
      'no_customers': 'No hay clientes registrados.',
      'no_announcements': 'No hay avisos publicados.',
    },

    // 🇮🇹 İTALYANCA (IT)
    'it': {
      'app_title': 'Ordini Rapidi & Micro',
      'login_subtitle': 'Accesso Negozio / Cliente',
      'username': 'Nome utente',
      'username_required': 'Inserisci nome utente',
      'password': 'Password',
      'password_required': 'Inserisci password',
      'login_btn': 'Accedi',
      'super_admin_warn': 'Super admin non disponibile da mobile.',
      'login_failed': 'Accesso fallito',
      'tab_menu': 'Menu',
      'tab_cart': 'Carrello',
      'tab_account': 'Mio Conto',
      'tab_orders': 'I Miei Ordini',
      'tab_products': 'Prodotti',
      'tab_options': 'Opzioni',
      'tab_categories': 'Categorie',
      'tab_customers': 'Clienti',
      'tab_announcements': 'Avvisi',
      'search_product': 'Cerca prodotto...',
      'all_categories': 'Tutti',
      'add_to_cart': 'Aggiungi al Carrello',
      'added_to_cart': 'Aggiunto al carrello',
      'out_of_stock': 'Esaurito',
      'cart_empty': 'Il carrello è vuoto.',
      'cart_title': 'Carrello',
      'clear_cart': 'Svuota Carrello',
      'order_note': 'Nota ordine',
      'total': 'Totale',
      'total_amount': 'Importo Totale',
      'confirm_order': 'Conferma Ordine',
      'order_received': 'Ordine ricevuto con successo!',
      'order_note_label': 'Nota',
      'options_label': 'Opzioni',
      'select_options': 'Scegli opzioni',
      'continue_btn': 'Continua',
      'cancel_btn': 'Annulla',
      'close_btn': 'Chiudi',
      'save_btn': 'Salva',
      'update_btn': 'Aggiorna',
      'delete_btn': 'Elimina',
      'yes_delete': 'Sì, Elimina',
      'account_summary': 'Riepilogo Conto',
      'unpaid_balance': 'Conto Aperto (Debito)',
      'total_paid': 'Totale Pagato',
      'period': 'Periodo',
      'period_all': 'Tutto',
      'period_daily': 'Oggi (Giornaliero)',
      'period_weekly': 'Questa Settimana (7 Giorni)',
      'period_monthly': 'Questo Mese (30 Giorni)',
      'payment_status': 'Pagamento',
      'pay_all': 'Tutti',
      'pay_unpaid': '⏳ Non Pagato (Aperto)',
      'pay_paid': '✅ Pagato (Storico)',
      'pay_cancelled': '❌ Annullato',
      'status_paid': 'PAGATO',
      'status_unpaid': 'NON PAGATO',
      'no_account_records': 'Nessun record trovato.',
      'no_filtered_records': 'Nessun record corrisponde al filtro.',
      'order_number': 'Ordine',
      'date': 'Data',
      'close_account_btn': 'Chiudi Conto',
      'all_orders_closed': 'Tutti gli ordini segnati come pagati.',
      'status_pending': 'In attesa',
      'status_accepted': 'Accettato',
      'status_preparing': 'In preparazione',
      'status_delivered': 'Consegnato',
      'status_cancelled': 'Annullato',
      'status_approved': 'Accetta',
      'status_cancel': 'Annulla Ordine',
      'shop_open': 'APERTO',
      'shop_closed': 'CHIUSO',
      'shop_open_tip': 'Negozio aperto',
      'shop_closed_tip': 'Negozio chiuso',
      'work_hours': 'Orario di Lavoro',
      'opening_time': 'Apertura',
      'closing_time': 'Chiusura',
      'auto_hours': 'Orari automatici attivi',
      'shop_closed_note': 'Nota di Chiusura',
      'shop_closed_note_hint': 'Es: Chiuso per lavori.',
      'shop_panel': 'Dashboard Negozio',
      'shop_owner_label': 'Proprietario',
      'customer_panel': 'Schermata Ordini Cliente',
      'logout': 'Esci',
      'refresh': 'Aggiorna',
      'add_product': 'Aggiungi Prodotto',
      'edit_product': 'Modifica Prodotto',
      'product_name': 'Nome Prodotto',
      'product_price': 'Prezzo',
      'product_desc': 'Descrizione',
      'product_img': 'URL Immagine',
      'gallery_btn': 'Galleria',
      'add_option': 'Aggiungi Opzione',
      'manage_options': 'Gestisci Opzioni',
      'add_category': 'Aggiungi Categoria',
      'edit_category': 'Modifica Categoria',
      'category_name': 'Nome Categoria',
      'add_customer': 'Aggiungi Cliente',
      'edit_customer': 'Modifica Cliente',
      'customer_name': 'Nome Cliente (Ufficio/Tavolo)',
      'customer_phone': 'Telefono',
      'customer_orders_history': 'Storico Conto e Ordini',
      'announcement_title': 'Titolo Avviso',
      'announcement_content': 'Testo Avviso',
      'add_announcement': 'Pubblica Avviso',
      'no_orders': 'Nessun ordine presente.',
      'no_products': 'Nessun prodotto presente.',
      'no_categories': 'Nessuna categoria presente.',
      'no_customers': 'Nessun cliente registrato.',
      'no_announcements': 'Nessun avviso presente.',
    },

    // 🇦🇿 AZERBAYCANCA (AZ)
    'az': {
      'app_title': 'Sürətli və Mikro Sifariş',
      'login_subtitle': 'Müəssisə / İstifadəçi Giriş Paneli',
      'username': 'İstifadəçi Adı',
      'username_required': 'İstifadəçi adını daxil edin',
      'password': 'Şifrə',
      'password_required': 'Şifrəni daxil edin',
      'login_btn': 'Daxil Ol',
      'super_admin_warn': 'Super admin hesabı mobil tətbiqdən açıla bilməz.',
      'login_failed': 'Giriş uğursuz oldu',
      'tab_menu': 'Menyu',
      'tab_cart': 'Səbətim',
      'tab_account': 'Hesabım',
      'tab_orders': 'Sifarişlərim',
      'tab_products': 'Məhsullar',
      'tab_options': 'Seçimlər',
      'tab_categories': 'Kateqoriyalar',
      'tab_customers': 'Müştərilər',
      'tab_announcements': 'Elanlar',
      'search_product': 'Məhsul axtar...',
      'all_categories': 'Hamısı',
      'add_to_cart': 'Səbətə Əlavə Et',
      'added_to_cart': 'Səbətə əlavə olundu',
      'out_of_stock': 'Bitdi',
      'cart_empty': 'Səbətiniz boşdur.',
      'cart_title': 'Səbətim',
      'clear_cart': 'Səbəti Təmizlə',
      'order_note': 'Sifariş Qeydi',
      'total': 'Cəmi',
      'total_amount': 'Ümumi Məbləğ',
      'confirm_order': 'Sifarişi Təsdiqlə',
      'order_received': 'Sifarişiniz qəbul edildi!',
      'order_note_label': 'Qeyd',
      'options_label': 'Seçimlər',
      'select_options': 'Seçimləri Müəyyən Edin',
      'continue_btn': 'Davam Et',
      'cancel_btn': 'Ləğv Et',
      'close_btn': 'Bağla',
      'save_btn': 'Yadda Saxla',
      'update_btn': 'Yenilə',
      'delete_btn': 'Sil',
      'yes_delete': 'Bəli, Sil',
      'account_summary': 'Hesab Xülasəsi',
      'unpaid_balance': 'Açıq Hesab (Borc)',
      'total_paid': 'Ümumi Ödənilən',
      'period': 'Dövr',
      'period_all': 'Hamısı',
      'period_daily': 'Bu gün (Günlük)',
      'period_weekly': 'Bu Həftə (7 Gün)',
      'period_monthly': 'Bu Ay (30 Gün)',
      'payment_status': 'Ödəniş',
      'pay_all': 'Hamısı',
      'pay_unpaid': '⏳ Ödənilməmiş (Açıq)',
      'pay_paid': '✅ Ödənilmiş (Keçmiş)',
      'pay_cancelled': '❌ Ləğv Edilmiş',
      'status_paid': 'ÖDƏNİLDİ',
      'status_unpaid': 'ÖDƏNİLMƏDİ',
      'no_account_records': 'Hesab qeydi tapılmadı.',
      'no_filtered_records': 'Filtrə uyğun qeyd tapılmadı.',
      'order_number': 'Sifariş',
      'date': 'Tarix',
      'close_account_btn': 'Hesabı Bağla',
      'all_orders_closed': 'Bütün gözləyən sifarişlər ödənildi kimi qeyd olundu.',
      'status_pending': 'Gözləyir',
      'status_accepted': 'Təsdiqləndi',
      'status_preparing': 'Hazırlanır',
      'status_delivered': 'Çatdırıldı',
      'status_cancelled': 'Ləğv edildi',
      'status_approved': 'Təsdiq Et',
      'status_cancel': 'Ləğv Et',
      'shop_open': 'AÇIQ',
      'shop_closed': 'BAĞLI',
      'shop_open_tip': 'Məkan Açıqdır',
      'shop_closed_tip': 'Məkan Bağlıdır',
      'work_hours': 'İş Saatları',
      'opening_time': 'Açılış Vaxtı',
      'closing_time': 'Bağlanış Vaxtı',
      'auto_hours': 'Avtomatik iş saatları aktivdir',
      'shop_closed_note': 'Bağlanış Qeydi',
      'shop_closed_note_hint': 'Məs: Təmir səbəbindən bağlıyıq.',
      'shop_panel': 'Məkan Paneli',
      'shop_owner_label': 'Məkan Sahibi',
      'customer_panel': 'Müştəri Sifariş Ekranı',
      'logout': 'Çıxış',
      'refresh': 'Yenilə',
      'add_product': 'Məhsul Əlavə Et',
      'edit_product': 'Məhsulu Düzəlt',
      'product_name': 'Məhsulun Adı',
      'product_price': 'Qiymət',
      'product_desc': 'Təsvir',
      'product_img': 'Şəkil Linki',
      'gallery_btn': 'Qalereya',
      'add_option': 'Seçim Əlavə Et',
      'manage_options': 'Seçimlərin İdarəsi',
      'add_category': 'Kateqoriya Əlavə Et',
      'edit_category': 'Kateqoriyanı Düzəlt',
      'category_name': 'Kateqoriya Adı',
      'add_customer': 'Müştəri Əlavə Et',
      'edit_customer': 'Müştərini Düzəlt',
      'customer_name': 'Müştərinin Adı (Ofis/Masa)',
      'customer_phone': 'Telefon Nömrəsi',
      'customer_orders_history': 'Hesab və Sifariş Tarixçəsi',
      'announcement_title': 'Elan Başlığı',
      'announcement_content': 'Elan Mətni',
      'add_announcement': 'Elan Paylaş',
      'no_orders': 'Hələ sifariş yoxdur.',
      'no_products': 'Hələ məhsul yoxdur.',
      'no_categories': 'Hələ kateqoriya yoxdur.',
      'no_customers': 'Qeydiyyatlı müştəri yoxdur.',
      'no_announcements': 'Elan yoxdur.',
    },

    // 🇮🇷 FARSÇA (FA)
    'fa': {
      'app_title': 'سفارش سریع و خرد',
      'login_subtitle': 'پنل ورود کسب و کار / مشتری',
      'username': 'نام کاربری',
      'username_required': 'لطفا نام کاربری را وارد کنید',
      'password': 'رمز عبور',
      'password_required': 'لطفا رمز عبور را وارد کنید',
      'login_btn': 'ورود',
      'super_admin_warn': 'ورود مدیر کل از طریق موبایل امکان پذیر نیست.',
      'login_failed': 'ورود ناموفق بود',
      'tab_menu': 'منو',
      'tab_cart': 'سبد خرید',
      'tab_account': 'حساب من',
      'tab_orders': 'سفارشات من',
      'tab_products': 'محصولات',
      'tab_options': 'گزینه‌ها',
      'tab_categories': 'دسته‌بندی‌ها',
      'tab_customers': 'مشتریان',
      'tab_announcements': 'اطلاعیه‌ها',
      'search_product': 'جستجوی محصول...',
      'all_categories': 'همه',
      'add_to_cart': 'افزودن به سبد',
      'added_to_cart': 'به سبد اضافه شد',
      'out_of_stock': 'تمام شد',
      'cart_empty': 'سبد خرید شما خالی است.',
      'cart_title': 'سبد خرید',
      'clear_cart': 'خالی کردن سبد',
      'order_note': 'یادداشت سفارش',
      'total': 'مجموع',
      'total_amount': 'مبلغ کل',
      'confirm_order': 'تایید سفارش',
      'order_received': 'سفارش شما با موفقیت ثبت شد!',
      'order_note_label': 'یادداشت',
      'options_label': 'گزینه‌ها',
      'select_options': 'انتخاب گزینه‌ها',
      'continue_btn': 'ادامه',
      'cancel_btn': 'انصراف',
      'close_btn': 'بستن',
      'save_btn': 'ذخیره',
      'update_btn': 'بروزرسانی',
      'delete_btn': 'حذف',
      'yes_delete': 'بله، حذف شود',
      'account_summary': 'خلاصه حساب',
      'unpaid_balance': 'حساب باز (بدهی)',
      'total_paid': 'مجموع پرداختی',
      'period': 'دوره',
      'period_all': 'همه',
      'period_daily': 'امروز (روزانه)',
      'period_weekly': 'این هفته (۷ روز)',
      'period_monthly': 'این ماه (۳۰ روز)',
      'payment_status': 'وضعیت پرداخت',
      'pay_all': 'همه',
      'pay_unpaid': '⏳ پرداخت نشده (باز)',
      'pay_paid': '✅ پرداخت شده (گذشته)',
      'pay_cancelled': '❌ لغو شده',
      'status_paid': 'پرداخت شد',
      'status_unpaid': 'پرداخت نشده',
      'no_account_records': 'هیچ رکوردی یافت نشد.',
      'no_filtered_records': 'موردی یافت نشد.',
      'order_number': 'سفارش',
      'date': 'تاریخ',
      'close_account_btn': 'تسویه حساب',
      'all_orders_closed': 'همه سفارشات به عنوان پرداخت شده ثبت شدند.',
      'status_pending': 'در انتظار',
      'status_accepted': 'تایید شد',
      'status_preparing': 'در حال آماده‌سازی',
      'status_delivered': 'تحویل داده شد',
      'status_cancelled': 'لغو شد',
      'status_approved': 'تایید',
      'status_cancel': 'لغو سفارش',
      'shop_open': 'باز',
      'shop_closed': 'بسته',
      'shop_open_tip': 'فروشگاه باز است',
      'shop_closed_tip': 'فروشگاه بسته است',
      'work_hours': 'ساعات کاری',
      'opening_time': 'ساعت بازگشایی',
      'closing_time': 'ساعت بستن',
      'auto_hours': 'ساعات کاری خودکار فعال',
      'shop_closed_note': 'علت تعطیلی',
      'shop_closed_note_hint': 'مثال: به دلیل بازسازی بسته است.',
      'shop_panel': 'پنل فروشگاه',
      'shop_owner_label': 'صاحب فروشگاه',
      'customer_panel': 'صفحه سفارش مشتری',
      'logout': 'خروج',
      'refresh': 'بروزرسانی',
      'add_product': 'افزودن محصول',
      'edit_product': 'ویرایش محصول',
      'product_name': 'نام محصول',
      'product_price': 'قیمت',
      'product_desc': 'توضیحات',
      'product_img': 'لینک تصویر',
      'gallery_btn': 'گالری',
      'add_option': 'افزودن گزینه',
      'manage_options': 'مدیریت گزینه‌ها',
      'add_category': 'افزودن دسته‌بندی',
      'edit_category': 'ویرایش دسته‌بندی',
      'category_name': 'نام دسته‌بندی',
      'add_customer': 'افزودن مشتری',
      'edit_customer': 'ویرایش مشتری',
      'customer_name': 'نام مشتری (دفتر/میز)',
      'customer_phone': 'شماره تلفن',
      'customer_orders_history': 'تاریخچه حساب و سفارشات',
      'announcement_title': 'عنوان اطلاعیه',
      'announcement_content': 'متن اطلاعیه',
      'add_announcement': 'انتشار اطلاعیه',
      'no_orders': 'هنوز سفارشی ثبت نشده است.',
      'no_products': 'هنوز محصولی وجود ندارد.',
      'no_categories': 'هنوز دسته‌بندی وجود ندارد.',
      'no_customers': 'هیچ مشتری ثبت نشده است.',
      'no_announcements': 'هیچ اطلاعیه‌ای وجود ندارد.',
    },

    // 🇵🇹 PORTEKİZCE (PT)
    'pt': {
      'app_title': 'Pedidos Rápidos & Micro',
      'login_subtitle': 'Portal de Acesso Empresa / Cliente',
      'username': 'Nome de Usuário',
      'username_required': 'Insira o nome de usuário',
      'password': 'Palavra-passe',
      'password_required': 'Insira a palavra-passe',
      'login_btn': 'Entrar',
      'super_admin_warn': 'Super admin não disponível no telemóvel.',
      'login_failed': 'Falha no início de sessão',
      'tab_menu': 'Menu',
      'tab_cart': 'Carrinho',
      'tab_account': 'Minha Conta',
      'tab_orders': 'Meus Pedidos',
      'tab_products': 'Produtos',
      'tab_options': 'Opções',
      'tab_categories': 'Categorias',
      'tab_customers': 'Clientes',
      'tab_announcements': 'Avisos',
      'search_product': 'Pesquisar produto...',
      'all_categories': 'Todos',
      'add_to_cart': 'Adicionar ao Carrinho',
      'added_to_cart': 'Adicionado ao carrinho',
      'out_of_stock': 'Esgotado',
      'cart_empty': 'O seu carrinho está vazio.',
      'cart_title': 'Carrinho',
      'clear_cart': 'Esvaziar Carrinho',
      'order_note': 'Nota do pedido',
      'total': 'Total',
      'total_amount': 'Montante Total',
      'confirm_order': 'Confirmar Pedido',
      'order_received': 'Pedido recebido com sucesso!',
      'order_note_label': 'Nota',
      'options_label': 'Opções',
      'select_options': 'Escolher opções',
      'continue_btn': 'Continuar',
      'cancel_btn': 'Cancelar',
      'close_btn': 'Fechar',
      'save_btn': 'Guardar',
      'update_btn': 'Atualizar',
      'delete_btn': 'Eliminar',
      'yes_delete': 'Sim, Eliminar',
      'account_summary': 'Resumo da Conta',
      'unpaid_balance': 'Conta Aberta (Dívida)',
      'total_paid': 'Total Pago',
      'period': 'Período',
      'period_all': 'Todo',
      'period_daily': 'Hoje (Diário)',
      'period_weekly': 'Esta Semana (7 Dias)',
      'period_monthly': 'Este Mês (30 Dias)',
      'payment_status': 'Pagamento',
      'pay_all': 'Todos',
      'pay_unpaid': '⏳ Não Pago (Aberto)',
      'pay_paid': '✅ Pago (Histórico)',
      'pay_cancelled': '❌ Cancelado',
      'status_paid': 'PAGO',
      'status_unpaid': 'NÃO PAGO',
      'no_account_records': 'Nenhum registo encontrado.',
      'no_filtered_records': 'Nenhum registo para este filtro.',
      'order_number': 'Pedido',
      'date': 'Data',
      'close_account_btn': 'Fechar Conta',
      'all_orders_closed': 'Todos os pedidos marcados como pagos.',
      'status_pending': 'Pendente',
      'status_accepted': 'Aceite',
      'status_preparing': 'A preparar',
      'status_delivered': 'Entregue',
      'status_cancelled': 'Cancelado',
      'status_approved': 'Aceitar',
      'status_cancel': 'Cancelar Pedido',
      'shop_open': 'ABERTO',
      'shop_closed': 'FECHADO',
      'shop_open_tip': 'Loja aberta',
      'shop_closed_tip': 'Loja fechada',
      'work_hours': 'Horário de Trabalho',
      'opening_time': 'Abertura',
      'closing_time': 'Fecho',
      'auto_hours': 'Horários automáticos ativos',
      'shop_closed_note': 'Nota de Encerramento',
      'shop_closed_note_hint': 'Ex: Fechado para obras.',
      'shop_panel': 'Painel da Loja',
      'shop_owner_label': 'Proprietário',
      'customer_panel': 'Ecrã de Pedidos',
      'logout': 'Sair',
      'refresh': 'Atualizar',
      'add_product': 'Adicionar Produto',
      'edit_product': 'Editar Produto',
      'product_name': 'Nome do Produto',
      'product_price': 'Preço',
      'product_desc': 'Descrição',
      'product_img': 'URL da Imagem',
      'gallery_btn': 'Galeria',
      'add_option': 'Adicionar Opção',
      'manage_options': 'Gerir Opções',
      'add_category': 'Adicionar Categoria',
      'edit_category': 'Editar Categoria',
      'category_name': 'Nome da Categoria',
      'add_customer': 'Adicionar Cliente',
      'edit_customer': 'Editar Cliente',
      'customer_name': 'Nome do Cliente',
      'customer_phone': 'Telefone',
      'customer_orders_history': 'Histórico de Conta e Pedidos',
      'announcement_title': 'Título do Aviso',
      'announcement_content': 'Conteúdo do Aviso',
      'add_announcement': 'Publicar Aviso',
      'no_orders': 'Ainda sem pedidos.',
      'no_products': 'Ainda sem produtos.',
      'no_categories': 'Ainda sem categorias.',
      'no_customers': 'Nenhum cliente registado.',
      'no_announcements': 'Nenhum aviso publicado.',
    },

    // 🇳🇱 FLEMENKÇE / HOLLANDACA (NL)
    'nl': {
      'app_title': 'Snelle & Micro Bestellingen',
      'login_subtitle': 'Bedrijf / Klant Inlogportaal',
      'username': 'Gebruikersnaam',
      'username_required': 'Vul gebruikersnaam in',
      'password': 'Wachtwoord',
      'password_required': 'Vul wachtwoord in',
      'login_btn': 'Inloggen',
      'super_admin_warn': 'Super admin niet beschikbaar via mobiel.',
      'login_failed': 'Inloggen mislukt',
      'tab_menu': 'Menu',
      'tab_cart': 'Winkelwagen',
      'tab_account': 'Mijn Rekening',
      'tab_orders': 'Mijn Bestellingen',
      'tab_products': 'Producten',
      'tab_options': 'Opties',
      'tab_categories': 'Categorieën',
      'tab_customers': 'Klanten',
      'tab_announcements': 'Mededelingen',
      'search_product': 'Product zoeken...',
      'all_categories': 'Alles',
      'add_to_cart': 'In Winkelwagen',
      'added_to_cart': 'Toegevoegd',
      'out_of_stock': 'Uitverkocht',
      'cart_empty': 'Uw winkelwagen is leeg.',
      'cart_title': 'Winkelwagen',
      'clear_cart': 'Winkelwagen Legen',
      'order_note': 'Bestelnotitie',
      'total': 'Totaal',
      'total_amount': 'Totaalbedrag',
      'confirm_order': 'Bestelling Bevestigen',
      'order_received': 'Bestelling succesvol ontvangen!',
      'order_note_label': 'Notitie',
      'options_label': 'Opties',
      'select_options': 'Kies opties',
      'continue_btn': 'Doorgaan',
      'cancel_btn': 'Annuleren',
      'close_btn': 'Sluiten',
      'save_btn': 'Opslaan',
      'update_btn': 'Bijwerken',
      'delete_btn': 'Verwijderen',
      'yes_delete': 'Ja, Verwijderen',
      'account_summary': 'Rekeningoverzicht',
      'unpaid_balance': 'Openstaand Saldo (Schuld)',
      'total_paid': 'Totaal Betaald',
      'period': 'Periode',
      'period_all': 'Alles',
      'period_daily': 'Vandaag (Dagelijks)',
      'period_weekly': 'Deze Week (7 Dagen)',
      'period_monthly': 'Deze Maand (30 Dagen)',
      'payment_status': 'Betaling',
      'pay_all': 'Alles',
      'pay_unpaid': '⏳ Onbetaald (Open)',
      'pay_paid': '✅ Betaald (Historie)',
      'pay_cancelled': '❌ Geannuleerd',
      'status_paid': 'BETAALD',
      'status_unpaid': 'ONBETAALD',
      'no_account_records': 'Geen gegevens gevonden.',
      'no_filtered_records': 'Geen resultaten voor deze filter.',
      'order_number': 'Bestelling',
      'date': 'Datum',
      'close_account_btn': 'Rekening Vereffenen',
      'all_orders_closed': 'Alle openstaande bestellingen gemarkeerd als betaald.',
      'status_pending': 'In afwachting',
      'status_accepted': 'Geaccepteerd',
      'status_preparing': 'In voorbereiding',
      'status_delivered': 'Bezorgd',
      'status_cancelled': 'Geannuleerd',
      'status_approved': 'Accepteren',
      'status_cancel': 'Bestelling Annuleren',
      'shop_open': 'OPEN',
      'shop_closed': 'GESLOTEN',
      'shop_open_tip': 'Winkel is open',
      'shop_closed_tip': 'Winkel is gesloten',
      'work_hours': 'Openingstijden',
      'opening_time': 'Opening',
      'closing_time': 'Sluiting',
      'auto_hours': 'Automatische openingstijden actief',
      'shop_closed_note': 'Sluitingsbericht',
      'shop_closed_note_hint': 'Bijv. Gesloten wegens verbouwing.',
      'shop_panel': 'Winkel Dashboard',
      'shop_owner_label': 'Eigenaar',
      'customer_panel': 'Klant Bestelscherm',
      'logout': 'Uitloggen',
      'refresh': 'Vernieuwen',
      'add_product': 'Product Toevoegen',
      'edit_product': 'Product Bewerken',
      'product_name': 'Productnaam',
      'product_price': 'Prijs',
      'product_desc': 'Beschrijving',
      'product_img': 'Afbeelding URL',
      'gallery_btn': 'Galerij',
      'add_option': 'Optie Toevoegen',
      'manage_options': 'Opties Beheren',
      'add_category': 'Categorie Toevoegen',
      'edit_category': 'Categorie Bewerken',
      'category_name': 'Categorienaam',
      'add_customer': 'Klant Toevoegen',
      'edit_customer': 'Klant Bewerken',
      'customer_name': 'Klantnaam (Kantoor/Tafel)',
      'customer_phone': 'Telefoonnummer',
      'customer_orders_history': 'Bestel- en Rekeninghistorie',
      'announcement_title': 'Titel van Mededeling',
      'announcement_content': 'Inhoud van Mededeling',
      'add_announcement': 'Mededeling Plaatsen',
      'no_orders': 'Nog geen bestellingen.',
      'no_products': 'Nog geen producten.',
      'no_categories': 'Nog geen categorieën.',
      'no_customers': 'Geen klanten geregistreerd.',
      'no_announcements': 'Geen mededelingen geplaatst.',
    },

    // 🇺🇦 UKRAYNACA (UK)
    'uk': {
      'app_title': 'Швидке та Мікро Замовлення',
      'login_subtitle': 'Вхід для Бізнесу / Клієнта',
      'username': 'Ім\'я користувача',
      'username_required': 'Введіть ім\'я користувача',
      'password': 'Пароль',
      'password_required': 'Введіть пароль',
      'login_btn': 'Увійти',
      'super_admin_warn': 'Супер-адміністратор не може увійти з мобільного.',
      'login_failed': 'Помилка входу',
      'tab_menu': 'Меню',
      'tab_cart': 'Кошик',
      'tab_account': 'Мій Рахунок',
      'tab_orders': 'Мої Замовлення',
      'tab_products': 'Товари',
      'tab_options': 'Опції',
      'tab_categories': 'Категорії',
      'tab_customers': 'Клієнти',
      'tab_announcements': 'Оголошення',
      'search_product': 'Пошук товару...',
      'all_categories': 'Всі',
      'add_to_cart': 'У Кошик',
      'added_to_cart': 'Додано у кошик',
      'out_of_stock': 'Закінчилось',
      'cart_empty': 'Ваш кошик порожній.',
      'cart_title': 'Кошик',
      'clear_cart': 'Очистити Кошик',
      'order_note': 'Примітка до замовлення',
      'total': 'Всього',
      'total_amount': 'Загальна Сума',
      'confirm_order': 'Підтвердити Замовлення',
      'order_received': 'Замовлення успішно прийнято!',
      'order_note_label': 'Примітка',
      'options_label': 'Опції',
      'select_options': 'Виберіть опції',
      'continue_btn': 'Продовжити',
      'cancel_btn': 'Скасувати',
      'close_btn': 'Закрити',
      'save_btn': 'Зберегти',
      'update_btn': 'Оновити',
      'delete_btn': 'Видалити',
      'yes_delete': 'Так, Видалити',
      'account_summary': 'Звіт за Рахунком',
      'unpaid_balance': 'Відкритий Рахунок (Борг)',
      'total_paid': 'Всього Сплачено',
      'period': 'Період',
      'period_all': 'Весь час',
      'period_daily': 'Сьогодні (День)',
      'period_weekly': 'Цей Тиждень (7 Днів)',
      'period_monthly': 'Цей Місяць (30 Днів)',
      'payment_status': 'Оплата',
      'pay_all': 'Всі',
      'pay_unpaid': '⏳ Не сплачено (Відкрито)',
      'pay_paid': '✅ Сплачено (Історія)',
      'pay_cancelled': '❌ Скасовано',
      'status_paid': 'СПЛАЧЕНО',
      'status_unpaid': 'НЕ СПЛАЧЕНО',
      'no_account_records': 'Записів не знайдено.',
      'no_filtered_records': 'Немає записів за фільтром.',
      'order_number': 'Замовлення',
      'date': 'Дата',
      'close_account_btn': 'Закрити Рахунок',
      'all_orders_closed': 'Всі очікувані замовлення позначено як сплачені.',
      'status_pending': 'В очікуванні',
      'status_accepted': 'Прийнято',
      'status_preparing': 'Готується',
      'status_delivered': 'Доставлено',
      'status_cancelled': 'Скасовано',
      'status_approved': 'Підтвердити',
      'status_cancel': 'Скасувати Замовлення',
      'shop_open': 'ВІДЧИНЕНО',
      'shop_closed': 'ЗАЧИНЕНО',
      'shop_open_tip': 'Заклад відчинено',
      'shop_closed_tip': 'Заклад зачинено',
      'work_hours': 'Години Роботи',
      'opening_time': 'Відкриття',
      'closing_time': 'Закриття',
      'auto_hours': 'Автоматичні години активні',
      'shop_closed_note': 'Причина закриття',
      'shop_closed_note_hint': 'напр. Зачинено на ремонт.',
      'shop_panel': 'Панель Закладу',
      'shop_owner_label': 'Власник',
      'customer_panel': 'Екран Замовлень Клієнта',
      'logout': 'Вийти',
      'refresh': 'Оновити',
      'add_product': 'Додати Товар',
      'edit_product': 'Редагувати Товар',
      'product_name': 'Назва Товару',
      'product_price': 'Ціна',
      'product_desc': 'Опис',
      'product_img': 'Посилання на фото',
      'gallery_btn': 'Галерея',
      'add_option': 'Додати Опцію',
      'manage_options': 'Керування Опціями',
      'add_category': 'Додати Категорію',
      'edit_category': 'Редагувати Категорію',
      'category_name': 'Назва Категорії',
      'add_customer': 'Додати Клієнта',
      'edit_customer': 'Редагувати Клієнта',
      'customer_name': 'Ім\'я Клієнта (Офіс/Стіл)',
      'customer_phone': 'Телефон',
      'customer_orders_history': 'Історія Рахунку та Замовлень',
      'announcement_title': 'Заголовок Оголошення',
      'announcement_content': 'Текст Оголошення',
      'add_announcement': 'Опублікувати Оголошення',
      'no_orders': 'Замовлень поки немає.',
      'no_products': 'Товарів поки немає.',
      'no_categories': 'Категорій поки немає.',
      'no_customers': 'Клієнти не зареєстровані.',
      'no_announcements': 'Оголошень немає.',
    },

    // 🇨🇳 ÇİNCE (ZH)
    'zh': {
      'app_title': '快捷与微型点餐系统',
      'login_subtitle': '商家 / 用户登录平台',
      'username': '用户名',
      'username_required': '请输入用户名',
      'password': '密码',
      'password_required': '请输入密码',
      'login_btn': '登录',
      'super_admin_warn': '超级管理员无法通过手机登录。',
      'login_failed': '登录失败',
      'tab_menu': '菜单',
      'tab_cart': '购物车',
      'tab_account': '我的账单',
      'tab_orders': '我的订单',
      'tab_products': '商品管理',
      'tab_options': '选项规格',
      'tab_categories': '分类管理',
      'tab_customers': '客户列表',
      'tab_announcements': '公告通知',
      'search_product': '搜索商品...',
      'all_categories': '全部',
      'add_to_cart': '加入购物车',
      'added_to_cart': '已加入购物车',
      'out_of_stock': '已售罄',
      'cart_empty': '您的购物车是空的。',
      'cart_title': '购物车',
      'clear_cart': '清空购物车',
      'order_note': '订单备注（例如：微辣、不加葱）',
      'total': '合计',
      'total_amount': '总金额',
      'confirm_order': '确认下单',
      'order_received': '订单已成功提交！',
      'order_note_label': '备注',
      'options_label': '选项',
      'select_options': '选择规格',
      'continue_btn': '继续',
      'cancel_btn': '取消',
      'close_btn': '关闭',
      'save_btn': '保存',
      'update_btn': '更新',
      'delete_btn': '删除',
      'yes_delete': '确定删除',
      'account_summary': '账单概览',
      'unpaid_balance': '未结账单（待付）',
      'total_paid': '已付总额',
      'period': '周期',
      'period_all': '全部',
      'period_daily': '今天（日报）',
      'period_weekly': '本周（7天）',
      'period_monthly': '本月（30天）',
      'payment_status': '支付状态',
      'pay_all': '全部',
      'pay_unpaid': '⏳ 未支付（挂账）',
      'pay_paid': '✅ 已支付（历史）',
      'pay_cancelled': '❌ 已取消',
      'status_paid': '已支付',
      'status_unpaid': '未支付',
      'no_account_records': '暂无账单记录。',
      'no_filtered_records': '没有符合条件的记录。',
      'order_number': '订单号',
      'date': '日期',
      'close_account_btn': '结清账单',
      'all_orders_closed': '所有待结订单已标记为已支付。',
      'status_pending': '待处理',
      'status_accepted': '已接单',
      'status_preparing': '制作中',
      'status_delivered': '已送达',
      'status_cancelled': '已取消',
      'status_approved': '接单',
      'status_cancel': '取消订单',
      'shop_open': '营业中',
      'shop_closed': '已打烊',
      'shop_open_tip': '店铺营业中',
      'shop_closed_tip': '店铺已打烊',
      'work_hours': '营业时间',
      'opening_time': '开门时间',
      'closing_time': '打烊时间',
      'auto_hours': '启用自动营业时间',
      'shop_closed_note': '打烊通知',
      'shop_closed_note_hint': '例如：店内装修暂停营业。',
      'shop_panel': '商家控制台',
      'shop_owner_label': '店主',
      'customer_panel': '客户点餐界面',
      'logout': '退出登录',
      'refresh': '刷新',
      'add_product': '添加商品',
      'edit_product': '编辑商品',
      'product_name': '商品名称',
      'product_price': '价格',
      'product_desc': '描述',
      'product_img': '图片链接',
      'gallery_btn': '相册',
      'add_option': '添加规格',
      'manage_options': '管理规格选项',
      'add_category': '添加分类',
      'edit_category': '编辑分类',
      'category_name': '分类名称',
      'add_customer': '添加客户',
      'edit_customer': '编辑客户',
      'customer_name': '客户姓名（办公室/桌号）',
      'customer_phone': '电话号码',
      'customer_orders_history': '账单与订单历史',
      'announcement_title': '公告标题',
      'announcement_content': '公告内容',
      'add_announcement': '发布公告',
      'no_orders': '暂无订单。',
      'no_products': '暂无商品。',
      'no_categories': '暂无分类。',
      'no_customers': '暂无注册客户。',
      'no_announcements': '暂无公告发布。',
    },

    // 🇯🇵 JAPONCA (JA)
    'ja': {
      'app_title': 'スピード＆マイクロ注文',
      'login_subtitle': '店舗・顧客ログインポータル',
      'username': 'ユーザー名',
      'username_required': 'ユーザー名を入力してください',
      'password': 'パスワード',
      'password_required': 'パスワードを入力してください',
      'login_btn': 'ログイン',
      'super_admin_warn': 'スーパー管理者はアプリからログインできません。',
      'login_failed': 'ログインに失敗しました',
      'tab_menu': 'メニュー',
      'tab_cart': 'カート',
      'tab_account': 'マイアカウント',
      'tab_orders': '注文履歴',
      'tab_products': '商品',
      'tab_options': 'オプション',
      'tab_categories': 'カテゴリー',
      'tab_customers': '顧客',
      'tab_announcements': 'お知らせ',
      'search_product': '商品を検索...',
      'all_categories': 'すべて',
      'add_to_cart': 'カートに追加',
      'added_to_cart': 'カートに追加しました',
      'out_of_stock': '売り切れ',
      'cart_empty': 'カートは空です。',
      'cart_title': 'カート',
      'clear_cart': 'カートを空にする',
      'order_note': '注文備考',
      'total': '合計',
      'total_amount': '合計金額',
      'confirm_order': '注文を確定する',
      'order_received': '注文が正常に送信されました！',
      'order_note_label': '備考',
      'options_label': 'オプション',
      'select_options': 'オプションを選択',
      'continue_btn': '続ける',
      'cancel_btn': 'キャンセル',
      'close_btn': '閉じる',
      'save_btn': '保存',
      'update_btn': '更新',
      'delete_btn': '削除',
      'yes_delete': 'はい、削除します',
      'account_summary': 'アカウント概要',
      'unpaid_balance': '未払い残高（掛け売り）',
      'total_paid': '支払い済み総額',
      'period': '期間',
      'period_all': '全期間',
      'period_daily': '本日（日次）',
      'period_weekly': '今週（7日間）',
      'period_monthly': '今月（30日間）',
      'payment_status': '支払い状況',
      'pay_all': 'すべて',
      'pay_unpaid': '⏳ 未払い（未精算）',
      'pay_paid': '✅ 支払い済み（履歴）',
      'pay_cancelled': '❌ キャンセル済み',
      'status_paid': '支払い済み',
      'status_unpaid': '未払い',
      'no_account_records': '記録が見つかりません。',
      'no_filtered_records': '該当する記録がありません。',
      'order_number': '注文番号',
      'date': '日付',
      'close_account_btn': 'アカウントを精算',
      'all_orders_closed': 'すべての未払い注文が精算済みになりました。',
      'status_pending': '受付中',
      'status_accepted': '承認済み',
      'status_preparing': '調理中',
      'status_delivered': '配達完了',
      'status_cancelled': 'キャンセル',
      'status_approved': '承認する',
      'status_cancel': '注文キャンセル',
      'shop_open': '営業中',
      'shop_closed': '準備中',
      'shop_open_tip': '営業中',
      'shop_closed_tip': '準備中',
      'work_hours': '営業時間',
      'opening_time': '開店時間',
      'closing_time': '閉店時間',
      'auto_hours': '自動営業時間を有効化',
      'shop_closed_note': '準備中・休業のお知らせ',
      'shop_closed_note_hint': '例: 店舗改装のため休業中',
      'shop_panel': '店舗管理パネル',
      'shop_owner_label': '店主',
      'customer_panel': '顧客注文画面',
      'logout': 'ログアウト',
      'refresh': '更新',
      'add_product': '商品を追加',
      'edit_product': '商品を編集',
      'product_name': '商品名',
      'product_price': '価格',
      'product_desc': '説明',
      'product_img': '画像URL',
      'gallery_btn': 'ギャラリー',
      'add_option': 'オプションを追加',
      'manage_options': 'オプション管理',
      'add_category': 'カテゴリーを追加',
      'edit_category': 'カテゴリーを編集',
      'category_name': 'カテゴリー名',
      'add_customer': '顧客を追加',
      'edit_customer': '顧客を編集',
      'customer_name': '顧客名（部署/テーブル）',
      'customer_phone': '電話番号',
      'customer_orders_history': '注文と掛け売り履歴',
      'announcement_title': 'お知らせタイトル',
      'announcement_content': 'お知らせ内容',
      'add_announcement': 'お知らせを投稿',
      'no_orders': '注文はまだありません。',
      'no_products': '商品はまだありません。',
      'no_categories': 'カテゴリーはまだありません。',
      'no_customers': '登録された顧客はいません。',
      'no_announcements': 'お知らせはありません。',
    },

    // 🇰🇷 KORECE (KO)
    'ko': {
      'app_title': '빠른 마이크로 주문',
      'login_subtitle': '매장 / 고객 로그인 포털',
      'username': '사용자 이름',
      'username_required': '사용자 이름을 입력하세요',
      'password': '비밀번호',
      'password_required': '비밀번호를 입력하세요',
      'login_btn': '로그인',
      'super_admin_warn': '슈퍼 관리자는 모바일에서 로그인할 수 없습니다.',
      'login_failed': '로그인 실패',
      'tab_menu': '메뉴',
      'tab_cart': '장바구니',
      'tab_account': '내 장부',
      'tab_orders': '주문 내역',
      'tab_products': '상품 관리',
      'tab_options': '옵션 관리',
      'tab_categories': '카테고리',
      'tab_customers': '고객 관리',
      'tab_announcements': '공지사항',
      'search_product': '상품 검색...',
      'all_categories': '전체',
      'add_to_cart': '장바구니 담기',
      'added_to_cart': '장바구니에 추가되었습니다',
      'out_of_stock': '품절',
      'cart_empty': '장바구니가 비어 있습니다.',
      'cart_title': '장바구니',
      'clear_cart': '장바구니 비우기',
      'order_note': '주문 요청사항',
      'total': '합계',
      'total_amount': '총 금액',
      'confirm_order': '주문하기',
      'order_received': '주문이 성공적으로 접수되었습니다!',
      'order_note_label': '요청사항',
      'options_label': '옵션',
      'select_options': '옵션 선택',
      'continue_btn': '계속',
      'cancel_btn': '취소',
      'close_btn': '닫기',
      'save_btn': '저장',
      'update_btn': '수정',
      'delete_btn': '삭제',
      'yes_delete': '네, 삭제합니다',
      'account_summary': '장부 요약',
      'unpaid_balance': '외상 잔액 (미수금)',
      'total_paid': '총 결제 금액',
      'period': '기간',
      'period_all': '전체',
      'period_daily': '오늘 (일간)',
      'period_weekly': '이번 주 (7일)',
      'period_monthly': '이번 달 (30일)',
      'payment_status': '결제 상태',
      'pay_all': '전체',
      'pay_unpaid': '⏳ 미결제 (외상)',
      'pay_paid': '✅ 결제완료 (내역)',
      'pay_cancelled': '❌ 취소됨',
      'status_paid': '결제완료',
      'status_unpaid': '미결제',
      'no_account_records': '장부 기록이 없습니다.',
      'no_filtered_records': '해당 조건의 기록이 없습니다.',
      'order_number': '주문번호',
      'date': '날짜',
      'close_account_btn': '장부 정산하기',
      'all_orders_closed': '모든 미결제 주문이 결제완료 처리되었습니다.',
      'status_pending': '대기중',
      'status_accepted': '접수됨',
      'status_preparing': '준비중',
      'status_delivered': '전달완료',
      'status_cancelled': '취소됨',
      'status_approved': '접수',
      'status_cancel': '주문 취소',
      'shop_open': '영업중',
      'shop_closed': '준비중',
      'shop_open_tip': '영업중',
      'shop_closed_tip': '준비중',
      'work_hours': '영업 시간',
      'opening_time': '오픈 시간',
      'closing_time': '마감 시간',
      'auto_hours': '자동 영업시간 활성화',
      'shop_closed_note': '마감 안내문',
      'shop_closed_note_hint': '예: 내부 공사로 인한 휴무',
      'shop_panel': '매장 관리자',
      'shop_owner_label': '점주',
      'customer_panel': '고객 주문 화면',
      'logout': '로그아웃',
      'refresh': '새로고침',
      'add_product': '상품 추가',
      'edit_product': '상품 수정',
      'product_name': '상품명',
      'product_price': '가격',
      'product_desc': '설명',
      'product_img': '이미지 URL',
      'gallery_btn': '갤러리',
      'add_option': '옵션 추가',
      'manage_options': '옵션 관리',
      'add_category': '카테고리 추가',
      'edit_category': '카테고리 수정',
      'category_name': '카테고리명',
      'add_customer': '고객 추가',
      'edit_customer': '고객 수정',
      'customer_name': '고객명 (부서/테이블)',
      'customer_phone': '전화번호',
      'customer_orders_history': '장부 및 주문 내역',
      'announcement_title': '공지 제목',
      'announcement_content': '공지 내용',
      'add_announcement': '공지 등록',
      'no_orders': '주문이 없습니다.',
      'no_products': '상품이 없습니다.',
      'no_categories': '카테고리가 없습니다.',
      'no_customers': '등록된 고객이 없습니다.',
      'no_announcements': '공지사항이 없습니다.',
    },
  };

  /// Metin çeviri fonksiyonu
  static String tr(String key) {
    final lang = currentLanguage;
    if (_localizedValues.containsKey(lang) && _localizedValues[lang]!.containsKey(key)) {
      return _localizedValues[lang]![key]!;
    }
    // İngilizceye bak
    if (_localizedValues['en'] != null && _localizedValues['en']!.containsKey(key)) {
      return _localizedValues['en']![key]!;
    }
    // Türkçeye bak
    if (_localizedValues['tr'] != null && _localizedValues['tr']!.containsKey(key)) {
      return _localizedValues['tr']![key]!;
    }
    return key;
  }
}

/// Kolay kullanım için String extension
extension StringLocaleExtension on String {
  String get tr => AppLocale.tr(this);
}
