// mobile/lib/services/app_localizations.dart

import 'dart:ui' as ui;
import 'package:flutter/foundation.dart';

class AppLocale {
  static String get currentLanguage {
    try {
      final code = ui.PlatformDispatcher.instance.locale.languageCode.toLowerCase();
      if (code == 'tr' || code == 'en' || code == 'de' || code == 'ar' || code == 'ru' || code == 'fr' || code == 'es') {
        return code;
      }
    } catch (_) {}
    return 'tr'; // Varsayılan Türkçe
  }

  static bool get isTurkish => currentLanguage == 'tr';
  static bool get isEnglish => currentLanguage == 'en';
  static bool get isArabic => currentLanguage == 'ar';

  static final Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      'app_title': 'Hızlı ve Micro Sipariş',
      'login_subtitle': 'İşletme / Kullanıcı Giriş Paneli',
      'username': 'Kullanıcı Adı',
      'username_required': 'Kullanıcı adı giriniz',
      'password': 'Şifre',
      'password_required': 'Şifre giriniz',
      'login_btn': 'Giriş Yap',
      'super_admin_warn': 'Süper admin hesabı mobil uygulamadan açılamaz. Lütfen Web Panelini kullanın.',
      'login_failed': 'Giriş başarısız',
      
      // Bottom Bar / Sekmeler
      'tab_menu': 'Menü',
      'tab_cart': 'Sepetim',
      'tab_account': 'Hesabım',
      'tab_orders': 'Siparişlerim',
      'tab_products': 'Ürünler',
      'tab_options': 'Seçenekler',
      'tab_categories': 'Kategoriler',
      'tab_customers': 'Müşteriler',
      'tab_announcements': 'Duyurular',

      // Müşteri Menü & Sepet
      'search_product': 'Ürün veya kategori ara...',
      'all_categories': 'Tümü',
      'add_to_cart': 'Sepete Ekle',
      'added_to_cart': 'Sepete eklendi',
      'out_of_stock': 'Tükendi',
      'cart_empty': 'Sepetiniz henüz boş.',
      'cart_title': 'Sepetim',
      'clear_cart': 'Sepeti Temizle',
      'order_note': 'Sipariş Notu (Örn: Acılı olsun, vb.)',
      'total': 'Toplam',
      'total_amount': 'Toplam Tutar',
      'confirm_order': 'Siparişi Onayla',
      'order_received': 'Siparişiniz başarıyla alındı!',
      'order_note_label': 'Not',
      'options_label': 'Seçenekler',
      'select_options': 'Seçenekleri Belirleyin',
      'continue_btn': 'Devam Et',
      'cancel_btn': 'Vazgeç',
      'close_btn': 'Kapat',
      'save_btn': 'Kaydet',
      'update_btn': 'Güncelle',
      'delete_btn': 'Sil',
      'yes_delete': 'Evet, Sil',

      // Hesap & Borç
      'account_summary': 'Hesap Özeti',
      'unpaid_balance': 'Açık Hesap (Borç)',
      'total_paid': 'Toplam Ödenen',
      'period': 'Dönem',
      'period_all': 'Tümü',
      'period_daily': 'Bugün (Günlük)',
      'period_weekly': 'Bu Hafta (7 Gün)',
      'period_monthly': 'Bu Ay (30 Gün)',
      'payment_status': 'Ödeme',
      'pay_all': 'Tümü',
      'pay_unpaid': '⏳ Ödenmemişler (Açık)',
      'pay_paid': '✅ Ödenenler (Geçmiş)',
      'pay_cancelled': '❌ İptal Edilenler',
      'status_paid': 'ÖDENDİ',
      'status_unpaid': 'ÖDENMEDİ',
      'no_account_records': 'Hesabınıza ait sipariş kaydı bulunmuyor.',
      'no_filtered_records': 'Seçilen filtreye ait kayıt bulunamadı.',
      'order_number': 'Sipariş',
      'date': 'Tarih',
      'close_account_btn': 'Hesabı Kapat',
      'all_orders_closed': 'Tüm bekleyen siparişler ödendi olarak kapatıldı.',

      // Sipariş Durumları
      'status_pending': 'Bekliyor',
      'status_accepted': 'Onaylandı',
      'status_preparing': 'Hazırlanıyor',
      'status_delivered': 'Teslim Edildi',
      'status_cancelled': 'İptal',
      'status_approved': 'Onayla',
      'status_cancel': 'İptal Et',

      // Dükkan Durumu & Mesai
      'shop_open': 'AÇIK',
      'shop_closed': 'KAPALI',
      'shop_open_tip': 'Dükkan Açık (Kapatmak için tıkla)',
      'shop_closed_tip': 'Dükkan Kapalı (Açmak için tıkla)',
      'work_hours': 'Mesai Saatleri',
      'opening_time': 'Açılış Saati',
      'closing_time': 'Kapanış Saati',
      'auto_hours': 'Otomatik Mesai Saatleri Aktif',
      'shop_closed_note': 'Kapanış Notu / Müşteri Bilgilendirmesi',
      'shop_closed_note_hint': 'Örn: Tadilat nedeniyle kapalıyız.',
      'shop_panel': 'Dükkan Paneli',
      'shop_owner_label': 'Dükkan Sahibi',
      'customer_panel': 'Müşteri Sipariş Ekranı',
      'logout': 'Çıkış',
      'refresh': 'Yenile',

      // Dükkan İşlemleri
      'add_product': 'Ürün Ekle',
      'edit_product': 'Ürün Düzenle',
      'product_name': 'Ürün Adı',
      'product_price': 'Fiyat (TL)',
      'product_desc': 'Açıklama',
      'product_img': 'Görsel Linki / URL',
      'gallery_btn': 'Galeri',
      'add_option': 'Seçenek Ekle',
      'manage_options': 'Ürün Seçenekleri Yönetimi',
      'add_category': 'Kategori Ekle',
      'edit_category': 'Kategori Düzenle',
      'category_name': 'Kategori Adı',
      'add_customer': 'Müşteri Ekle',
      'edit_customer': 'Müşteriyi Düzenle',
      'customer_name': 'Müşteri Ad Soyad (Ofis/Masa No)',
      'customer_phone': 'Telefon Numarası',
      'customer_orders_history': 'Hesap & Sipariş Geçmişi',
      'announcement_title': 'Duyuru Başlığı',
      'announcement_content': 'Duyuru Metni',
      'add_announcement': 'Duyuru Yayınla',
      'no_orders': 'Henüz sipariş yok.',
      'no_products': 'Henüz ürün yok.',
      'no_categories': 'Henüz kategori yok.',
      'no_customers': 'Kayıtlı müşteri yok.',
      'no_announcements': 'Yayınlanmış duyuru yok.',
    },
    'en': {
      'app_title': 'Quick & Micro Order',
      'login_subtitle': 'Business / Customer Login Portal',
      'username': 'Username',
      'username_required': 'Please enter username',
      'password': 'Password',
      'password_required': 'Please enter password',
      'login_btn': 'Sign In',
      'super_admin_warn': 'Super admin cannot log in via mobile. Please use the Web Panel.',
      'login_failed': 'Login failed',

      // Bottom Bar / Tabs
      'tab_menu': 'Menu',
      'tab_cart': 'Cart',
      'tab_account': 'My Account',
      'tab_orders': 'My Orders',
      'tab_products': 'Products',
      'tab_options': 'Options',
      'tab_categories': 'Categories',
      'tab_customers': 'Customers',
      'tab_announcements': 'Notices',

      // Customer Menu & Cart
      'search_product': 'Search product or category...',
      'all_categories': 'All',
      'add_to_cart': 'Add to Cart',
      'added_to_cart': 'Added to cart',
      'out_of_stock': 'Out of Stock',
      'cart_empty': 'Your cart is empty.',
      'cart_title': 'My Cart',
      'clear_cart': 'Clear Cart',
      'order_note': 'Order Note (e.g., extra sauce, no onions)',
      'total': 'Total',
      'total_amount': 'Total Amount',
      'confirm_order': 'Confirm Order',
      'order_received': 'Your order has been received!',
      'order_note_label': 'Note',
      'options_label': 'Options',
      'select_options': 'Choose Options',
      'continue_btn': 'Continue',
      'cancel_btn': 'Cancel',
      'close_btn': 'Close',
      'save_btn': 'Save',
      'update_btn': 'Update',
      'delete_btn': 'Delete',
      'yes_delete': 'Yes, Delete',

      // Account & Balance
      'account_summary': 'Account Summary',
      'unpaid_balance': 'Open Balance (Debt)',
      'total_paid': 'Total Paid',
      'period': 'Period',
      'period_all': 'All Time',
      'period_daily': 'Today (Daily)',
      'period_weekly': 'This Week (7 Days)',
      'period_monthly': 'This Month (30 Days)',
      'payment_status': 'Payment',
      'pay_all': 'All',
      'pay_unpaid': '⏳ Unpaid (Open)',
      'pay_paid': '✅ Paid (Past)',
      'pay_cancelled': '❌ Cancelled',
      'status_paid': 'PAID',
      'status_unpaid': 'UNPAID',
      'no_account_records': 'No account records found.',
      'no_filtered_records': 'No records match the selected filter.',
      'order_number': 'Order',
      'date': 'Date',
      'close_account_btn': 'Settle Account',
      'all_orders_closed': 'All pending orders marked as paid.',

      // Order Statuses
      'status_pending': 'Pending',
      'status_accepted': 'Accepted',
      'status_preparing': 'Preparing',
      'status_delivered': 'Delivered',
      'status_cancelled': 'Cancelled',
      'status_approved': 'Accept',
      'status_cancel': 'Cancel Order',

      // Shop Status & Work Hours
      'shop_open': 'OPEN',
      'shop_closed': 'CLOSED',
      'shop_open_tip': 'Shop is Open (Click to close)',
      'shop_closed_tip': 'Shop is Closed (Click to open)',
      'work_hours': 'Operating Hours',
      'opening_time': 'Opening Time',
      'closing_time': 'Closing Time',
      'auto_hours': 'Enable Auto Hours',
      'shop_closed_note': 'Closure Notice / Customer Info',
      'shop_closed_note_hint': 'e.g., Closed for renovation.',
      'shop_panel': 'Shop Dashboard',
      'shop_owner_label': 'Shop Owner',
      'customer_panel': 'Customer Order Screen',
      'logout': 'Log Out',
      'refresh': 'Refresh',

      // Shop Actions
      'add_product': 'Add Product',
      'edit_product': 'Edit Product',
      'product_name': 'Product Name',
      'product_price': 'Price',
      'product_desc': 'Description',
      'product_img': 'Image URL',
      'gallery_btn': 'Gallery',
      'add_option': 'Add Option',
      'manage_options': 'Product Options Management',
      'add_category': 'Add Category',
      'edit_category': 'Edit Category',
      'category_name': 'Category Name',
      'add_customer': 'Add Customer',
      'edit_customer': 'Edit Customer',
      'customer_name': 'Customer Full Name (Office/Desk)',
      'customer_phone': 'Phone Number',
      'customer_orders_history': 'Account & Order History',
      'announcement_title': 'Notice Title',
      'announcement_content': 'Notice Content',
      'add_announcement': 'Post Notice',
      'no_orders': 'No orders yet.',
      'no_products': 'No products yet.',
      'no_categories': 'No categories yet.',
      'no_customers': 'No customers registered.',
      'no_announcements': 'No notices posted.',
    },
    'de': {
      'app_title': 'Schnell- & Mikrobestsystem',
      'login_subtitle': 'Betrieb / Kunden Login Portal',
      'username': 'Benutzername',
      'username_required': 'Bitte Benutzernamen eingeben',
      'password': 'Passwort',
      'password_required': 'Bitte Passwort eingeben',
      'login_btn': 'Anmelden',
      'super_admin_warn': 'Super-Admin kann sich nicht mobil anmelden. Bitte Web-Panel nutzen.',
      'login_failed': 'Anmeldung fehlgeschlagen',

      // Bottom Bar
      'tab_menu': 'Menü',
      'tab_cart': 'Warenkorb',
      'tab_account': 'Mein Konto',
      'tab_orders': 'Bestellungen',
      'tab_products': 'Produkte',
      'tab_options': 'Optionen',
      'tab_categories': 'Kategorien',
      'tab_customers': 'Kunden',
      'tab_announcements': 'Mitteilungen',

      // Menu & Cart
      'search_product': 'Produkt oder Kategorie suchen...',
      'all_categories': 'Alle',
      'add_to_cart': 'In den Warenkorb',
      'added_to_cart': 'Hinzugefügt',
      'out_of_stock': 'Ausverkauft',
      'cart_empty': 'Ihr Warenkorb ist leer.',
      'cart_title': 'Warenkorb',
      'clear_cart': 'Warenkorb leeren',
      'order_note': 'Bestellnotiz (z.B. ohne Zwiebeln)',
      'total': 'Gesamt',
      'total_amount': 'Gesamtbetrag',
      'confirm_order': 'Bestellung aufgeben',
      'order_received': 'Bestellung erfolgreich eingegangen!',
      'order_note_label': 'Notiz',
      'options_label': 'Optionen',
      'select_options': 'Optionen wählen',
      'continue_btn': 'Weiter',
      'cancel_btn': 'Abbrechen',
      'close_btn': 'Schließen',
      'save_btn': 'Speichern',
      'update_btn': 'Aktualisieren',
      'delete_btn': 'Löschen',
      'yes_delete': 'Ja, Löschen',

      // Balance
      'account_summary': 'Kontoübersicht',
      'unpaid_balance': 'Offener Betrag (Schulden)',
      'total_paid': 'Gesamt Bezahlt',
      'period': 'Zeitraum',
      'period_all': 'Alle',
      'period_daily': 'Heute (Täglich)',
      'period_weekly': 'Diese Woche (7 Tage)',
      'period_monthly': 'Diesen Monat (30 Tage)',
      'payment_status': 'Zahlung',
      'pay_all': 'Alle',
      'pay_unpaid': '⏳ Unbezahlt (Offen)',
      'pay_paid': '✅ Bezahlt (Historie)',
      'pay_cancelled': '❌ Storniert',
      'status_paid': 'BEZAHLT',
      'status_unpaid': 'OFFEN',
      'no_account_records': 'Keine Kontoeinträge gefunden.',
      'no_filtered_records': 'Keine Einträge für den Filter.',
      'order_number': 'Bestellung',
      'date': 'Datum',
      'close_account_btn': 'Konto ausgleichen',
      'all_orders_closed': 'Alle offenen Bestellungen als bezahlt markiert.',

      // Status
      'status_pending': 'Wartend',
      'status_accepted': 'Akzeptiert',
      'status_preparing': 'Wird zubereitet',
      'status_delivered': 'Geliefert',
      'status_cancelled': 'Storniert',
      'status_approved': 'Bestätigen',
      'status_cancel': 'Stornieren',

      // Shop
      'shop_open': 'GEÖFFNET',
      'shop_closed': 'GESCHLOSSEN',
      'shop_open_tip': 'Laden geöffnet (Klicken zum Schließen)',
      'shop_closed_tip': 'Laden geschlossen (Klicken zum Öffnen)',
      'work_hours': 'Öffnungszeiten',
      'opening_time': 'Öffnung',
      'closing_time': 'Schließung',
      'auto_hours': 'Automatische Öffnungszeiten',
      'shop_closed_note': 'Schließungsgrund / Info',
      'shop_closed_note_hint': 'z.B. Wegen Renovierung geschlossen.',
      'shop_panel': 'Laden-Dashboard',
      'shop_owner_label': 'Inhaber',
      'customer_panel': 'Kunden-Bestellansicht',
      'logout': 'Abmelden',
      'refresh': 'Aktualisieren',

      // Actions
      'add_product': 'Produkt hinzufügen',
      'edit_product': 'Produkt bearbeiten',
      'product_name': 'Produktname',
      'product_price': 'Preis',
      'product_desc': 'Beschreibung',
      'product_img': 'Bild-URL',
      'gallery_btn': 'Galerie',
      'add_option': 'Option hinzufügen',
      'manage_options': 'Optionen verwalten',
      'add_category': 'Kategorie hinzufügen',
      'edit_category': 'Kategorie bearbeiten',
      'category_name': 'Kategoriename',
      'add_customer': 'Kunde hinzufügen',
      'edit_customer': 'Kunde bearbeiten',
      'customer_name': 'Kundenname (Büro/Tisch)',
      'customer_phone': 'Telefonnummer',
      'customer_orders_history': 'Konto- & Bestellhistorie',
      'announcement_title': 'Titel der Mitteilung',
      'announcement_content': 'Inhalt der Mitteilung',
      'add_announcement': 'Mitteilung veröffentlichen',
      'no_orders': 'Noch keine Bestellungen.',
      'no_products': 'Noch keine Produkte.',
      'no_categories': 'Noch keine Kategorien.',
      'no_customers': 'Keine Kunden registriert.',
      'no_announcements': 'Keine Mitteilungen vorhanden.',
    },
    'ar': {
      'app_title': 'نظام الطلب السريع',
      'login_subtitle': 'لوحة دخول المتجر / العميل',
      'username': 'اسم المستخدم',
      'username_required': 'يرجى إدخال اسم المستخدم',
      'password': 'كلمة المرور',
      'password_required': 'يرجى إدخال كلمة المرور',
      'login_btn': 'تسجيل الدخول',
      'super_admin_warn': 'لا يمكن تسجيل دخول المشرف العام عبر التطبيق. يرجى استخدام لوحة الويب.',
      'login_failed': 'فشل تسجيل الدخول',

      // Bottom Bar
      'tab_menu': 'القائمة',
      'tab_cart': 'سلتي',
      'tab_account': 'حسابي',
      'tab_orders': 'طلباتي',
      'tab_products': 'المنتجات',
      'tab_options': 'الخيارات',
      'tab_categories': 'الأقسام',
      'tab_customers': 'الزبائن',
      'tab_announcements': 'الإعلانات',

      // Menu & Cart
      'search_product': 'البحث عن منتج أو قسم...',
      'all_categories': 'الكل',
      'add_to_cart': 'إضافة إلى السلة',
      'added_to_cart': 'تمت الإضافة للسلة',
      'out_of_stock': 'نفدت الكمية',
      'cart_empty': 'سلة التسوق فارغة.',
      'cart_title': 'سلة التسوق',
      'clear_cart': 'إفراغ السلة',
      'order_note': 'ملاحظة الطلب (مثال: بدون بصل، زيادة صوص)',
      'total': 'المجموع',
      'total_amount': 'المجموع الكلي',
      'confirm_order': 'تأكيد الطلب',
      'order_received': 'تم استلام طلبك بنجاح!',
      'order_note_label': 'ملاحظة',
      'options_label': 'الخيارات',
      'select_options': 'حدد الخيارات',
      'continue_btn': 'متابعة',
      'cancel_btn': 'إلغاء',
      'close_btn': 'إغلاق',
      'save_btn': 'حفظ',
      'update_btn': 'تحديث',
      'delete_btn': 'حذف',
      'yes_delete': 'نعم، احذف',

      // Balance
      'account_summary': 'ملخص الحساب',
      'unpaid_balance': 'الحساب المفتوح (الديون)',
      'total_paid': 'المبلغ المدفوع',
      'period': 'الفترة',
      'period_all': 'الكل',
      'period_daily': 'اليوم (يومي)',
      'period_weekly': 'هذا الأسبوع (7 أيام)',
      'period_monthly': 'هذا الشهر (30 يوماً)',
      'payment_status': 'الدفع',
      'pay_all': 'الكل',
      'pay_unpaid': '⏳ غير مدفوع (مفتوح)',
      'pay_paid': '✅ مدفوع (سابق)',
      'pay_cancelled': '❌ ملغي',
      'status_paid': 'مدفوع',
      'status_unpaid': 'غير مدفوع',
      'no_account_records': 'لا توجد سجلات حساب.',
      'no_filtered_records': 'لا توجد نتائج للتصفية المحددة.',
      'order_number': 'طلب',
      'date': 'التاريخ',
      'close_account_btn': 'إغلاق الحساب',
      'all_orders_closed': 'تم تعيين جميع الطلبات المعلقة كمدفوعة.',

      // Status
      'status_pending': 'قيد الانتظار',
      'status_accepted': 'تم القبول',
      'status_preparing': 'قيد التحضير',
      'status_delivered': 'تم التسليم',
      'status_cancelled': 'ملغي',
      'status_approved': 'قبول',
      'status_cancel': 'إلغاء الطلب',

      // Shop
      'shop_open': 'مفتوح',
      'shop_closed': 'مغلق',
      'shop_open_tip': 'المتجر مفتوح (اضغط للإغلاق)',
      'shop_closed_tip': 'المتجر مغلق (اضغط للفتح)',
      'work_hours': 'ساعات العمل',
      'opening_time': 'وقت الافتتاح',
      'closing_time': 'وقت الإغلاق',
      'auto_hours': 'تفعيل ساعات العمل التلقائية',
      'shop_closed_note': 'سبب الإغلاق / ملاحظة للعملاء',
      'shop_closed_note_hint': 'مثال: مغلق لأعمال الصيانة.',
      'shop_panel': 'لوحة المتجر',
      'shop_owner_label': 'صاحب المتجر',
      'customer_panel': 'شاشة طلبات الزبائن',
      'logout': 'تسجيل الخروج',
      'refresh': 'تحديث',

      // Actions
      'add_product': 'إضافة منتج',
      'edit_product': 'تعديل منتج',
      'product_name': 'اسم المنتج',
      'product_price': 'السعر',
      'product_desc': 'الوصف',
      'product_img': 'رابط الصورة',
      'gallery_btn': 'المعرض',
      'add_option': 'إضافة خيار',
      'manage_options': 'إدارة خيارات المنتجات',
      'add_category': 'إضافة قسم',
      'edit_category': 'تعديل القسم',
      'category_name': 'اسم القسم',
      'add_customer': 'إضافة زبون',
      'edit_customer': 'تعديل بيانات الزبون',
      'customer_name': 'اسم الزبون (المكتب/الطاولة)',
      'customer_phone': 'رقم الهاتف',
      'customer_orders_history': 'سجل الحساب والطلبات',
      'announcement_title': 'عنوان الإعلان',
      'announcement_content': 'نص الإعلان',
      'add_announcement': 'نشر إعلان',
      'no_orders': 'لا توجد طلبات بعد.',
      'no_products': 'لا توجد منتجات بعد.',
      'no_categories': 'لا توجد أقسام بعد.',
      'no_customers': 'لا يوجد زبائن مسجلون.',
      'no_announcements': 'لا توجد إعلانات منشورة.',
    },
    'ru': {
      'app_title': 'Быстрый и Микро Заказ',
      'login_subtitle': 'Панель Входа Бизнес / Клиент',
      'username': 'Имя пользователя',
      'username_required': 'Введите имя пользователя',
      'password': 'Пароль',
      'password_required': 'Введите пароль',
      'login_btn': 'Войти',
      'super_admin_warn': 'Супер-администратор не может войти через мобильное приложение. Используйте веб-панель.',
      'login_failed': 'Ошибка входа',

      // Bottom Bar
      'tab_menu': 'Меню',
      'tab_cart': 'Корзина',
      'tab_account': 'Мой счет',
      'tab_orders': 'Мои заказы',
      'tab_products': 'Товары',
      'tab_options': 'Опции',
      'tab_categories': 'Категории',
      'tab_customers': 'Клиенты',
      'tab_announcements': 'Объявления',

      // Menu & Cart
      'search_product': 'Поиск товара или категории...',
      'all_categories': 'Все',
      'add_to_cart': 'В корзину',
      'added_to_cart': 'Добавлено в корзину',
      'out_of_stock': 'Нет в наличии',
      'cart_empty': 'Ваша корзина пуста.',
      'cart_title': 'Корзина',
      'clear_cart': 'Очистить корзину',
      'order_note': 'Примечание к заказу (напр. без лука)',
      'total': 'Итого',
      'total_amount': 'Общая сумма',
      'confirm_order': 'Подтвердить заказ',
      'order_received': 'Ваш заказ успешно принят!',
      'order_note_label': 'Примечание',
      'options_label': 'Опции',
      'select_options': 'Выберите опции',
      'continue_btn': 'Продолжить',
      'cancel_btn': 'Отмена',
      'close_btn': 'Закрыть',
      'save_btn': 'Сохранить',
      'update_btn': 'Обновить',
      'delete_btn': 'Удалить',
      'yes_delete': 'Да, удалить',

      // Balance
      'account_summary': 'Сводка по счету',
      'unpaid_balance': 'Открытый счет (Долг)',
      'total_paid': 'Всего оплачено',
      'period': 'Период',
      'period_all': 'Все время',
      'period_daily': 'Сегодня (День)',
      'period_weekly': 'Эта неделя (7 дней)',
      'period_monthly': 'Этот месяц (30 дней)',
      'payment_status': 'Оплата',
      'pay_all': 'Все',
      'pay_unpaid': '⏳ Не оплачено (Открыто)',
      'pay_paid': '✅ Оплачено (История)',
      'pay_cancelled': '❌ Отменено',
      'status_paid': 'ОПЛАЧЕНО',
      'status_unpaid': 'НЕ ОПЛАЧЕНО',
      'no_account_records': 'Записи по счету не найдены.',
      'no_filtered_records': 'Нет записей по выбранному фильтру.',
      'order_number': 'Заказ',
      'date': 'Дата',
      'close_account_btn': 'Закрыть счет',
      'all_orders_closed': 'Все ожидающие заказы отмечены как оплаченные.',

      // Status
      'status_pending': 'В ожидании',
      'status_accepted': 'Принят',
      'status_preparing': 'Готовится',
      'status_delivered': 'Доставлен',
      'status_cancelled': 'Отменен',
      'status_approved': 'Подтвердить',
      'status_cancel': 'Отменить заказ',

      // Shop
      'shop_open': 'ОТКРЫТО',
      'shop_closed': 'ЗАКРЫТО',
      'shop_open_tip': 'Заведение открыто (нажмите, чтобы закрыть)',
      'shop_closed_tip': 'Заведение закрыто (нажмите, чтобы открыть)',
      'work_hours': 'Часы работы',
      'opening_time': 'Время открытия',
      'closing_time': 'Время закрытия',
      'auto_hours': 'Автоматические часы работы',
      'shop_closed_note': 'Причина закрытия / Информация',
      'shop_closed_note_hint': 'напр. Закрыто на ремонт.',
      'shop_panel': 'Панель управления',
      'shop_owner_label': 'Владелец',
      'customer_panel': 'Экран заказов клиента',
      'logout': 'Выйти',
      'refresh': 'Обновить',

      // Actions
      'add_product': 'Добавить товар',
      'edit_product': 'Редактировать товар',
      'product_name': 'Название товара',
      'product_price': 'Цена',
      'product_desc': 'Описание',
      'product_img': 'Ссылка на фото',
      'gallery_btn': 'Галерея',
      'add_option': 'Добавить опцию',
      'manage_options': 'Управление опциями',
      'add_category': 'Добавить категорию',
      'edit_category': 'Редактировать категорию',
      'category_name': 'Название категории',
      'add_customer': 'Добавить клиента',
      'edit_customer': 'Редактировать клиента',
      'customer_name': 'ФИО клиента (Офис/Стол)',
      'customer_phone': 'Номер телефона',
      'customer_orders_history': 'История счета и заказов',
      'announcement_title': 'Заголовок объявления',
      'announcement_content': 'Текст объявления',
      'add_announcement': 'Опубликовать объявление',
      'no_orders': 'Заказов пока нет.',
      'no_products': 'Товаров пока нет.',
      'no_categories': 'Категорий пока нет.',
      'no_customers': 'Клиенты не зарегистрированы.',
      'no_announcements': 'Нет объявлений.',
    },
    'fr': {
      'app_title': 'Commande Rapide & Micro',
      'login_subtitle': 'Portail de Connexion Entreprise / Client',
      'username': 'Nom d\'utilisateur',
      'username_required': 'Veuillez entrer un nom d\'utilisateur',
      'password': 'Mot de passe',
      'password_required': 'Veuillez entrer un mot de passe',
      'login_btn': 'Se connecter',
      'super_admin_warn': 'Le super admin ne peut pas se connecter sur mobile. Utilisez le panneau Web.',
      'login_failed': 'Échec de connexion',

      // Bottom Bar
      'tab_menu': 'Menu',
      'tab_cart': 'Panier',
      'tab_account': 'Mon Compte',
      'tab_orders': 'Mes Commandes',
      'tab_products': 'Produits',
      'tab_options': 'Options',
      'tab_categories': 'Catégories',
      'tab_customers': 'Clients',
      'tab_announcements': 'Annonces',

      // Menu & Cart
      'search_product': 'Rechercher un produit ou catégorie...',
      'all_categories': 'Tout',
      'add_to_cart': 'Ajouter au panier',
      'added_to_cart': 'Ajouté au panier',
      'out_of_stock': 'Épuisé',
      'cart_empty': 'Votre panier est vide.',
      'cart_title': 'Mon Panier',
      'clear_cart': 'Vider le panier',
      'order_note': 'Note de commande (ex: sans oignons)',
      'total': 'Total',
      'total_amount': 'Montant Total',
      'confirm_order': 'Confirmer la commande',
      'order_received': 'Votre commande a été reçue !',
      'order_note_label': 'Note',
      'options_label': 'Options',
      'select_options': 'Choisir les options',
      'continue_btn': 'Continuer',
      'cancel_btn': 'Annuler',
      'close_btn': 'Fermer',
      'save_btn': 'Enregistrer',
      'update_btn': 'Mettre à jour',
      'delete_btn': 'Supprimer',
      'yes_delete': 'Oui, Supprimer',

      // Balance
      'account_summary': 'Résumé du Compte',
      'unpaid_balance': 'Compte Ouvert (Dette)',
      'total_paid': 'Total Payé',
      'period': 'Période',
      'period_all': 'Tout',
      'period_daily': 'Aujourd\'hui (Quotidien)',
      'period_weekly': 'Cette Semaine (7 Jours)',
      'period_monthly': 'Ce Mois (30 Jours)',
      'payment_status': 'Paiement',
      'pay_all': 'Tout',
      'pay_unpaid': '⏳ Non Payé (Ouvert)',
      'pay_paid': '✅ Payé (Historique)',
      'pay_cancelled': '❌ Annulé',
      'status_paid': 'PAYÉ',
      'status_unpaid': 'NON PAYÉ',
      'no_account_records': 'Aucun historique de compte trouvé.',
      'no_filtered_records': 'Aucun enregistrement pour ce filtre.',
      'order_number': 'Commande',
      'date': 'Date',
      'close_account_btn': 'Régler le compte',
      'all_orders_closed': 'Toutes les commandes en attente sont marquées comme payées.',

      // Status
      'status_pending': 'En attente',
      'status_accepted': 'Acceptée',
      'status_preparing': 'En préparation',
      'status_delivered': 'Livrée',
      'status_cancelled': 'Annulée',
      'status_approved': 'Accepter',
      'status_cancel': 'Annuler',

      // Shop
      'shop_open': 'OUVERT',
      'shop_closed': 'FERMÉ',
      'shop_open_tip': 'Boutique ouverte (cliquer pour fermer)',
      'shop_closed_tip': 'Boutique fermée (cliquer pour ouvrir)',
      'work_hours': 'Heures d\'ouverture',
      'opening_time': 'Heure d\'ouverture',
      'closing_time': 'Heure de fermeture',
      'auto_hours': 'Heures automatiques activées',
      'shop_closed_note': 'Motif de fermeture / Info client',
      'shop_closed_note_hint': 'ex: Fermé pour rénovation.',
      'shop_panel': 'Tableau de Bord',
      'shop_owner_label': 'Propriétaire',
      'customer_panel': 'Écran de commande client',
      'logout': 'Déconnexion',
      'refresh': 'Actualiser',

      // Actions
      'add_product': 'Ajouter un produit',
      'edit_product': 'Modifier le produit',
      'product_name': 'Nom du produit',
      'product_price': 'Prix',
      'product_desc': 'Description',
      'product_img': 'URL de l\'image',
      'gallery_btn': 'Galerie',
      'add_option': 'Ajouter une option',
      'manage_options': 'Gérer les options',
      'add_category': 'Ajouter une catégorie',
      'edit_category': 'Modifier la catégorie',
      'category_name': 'Nom de la catégorie',
      'add_customer': 'Ajouter un client',
      'edit_customer': 'Modifier le client',
      'customer_name': 'Nom du client (Bureau/Table)',
      'customer_phone': 'Numéro de téléphone',
      'customer_orders_history': 'Historique Compte & Commandes',
      'announcement_title': 'Titre de l\'annonce',
      'announcement_content': 'Contenu de l\'annonce',
      'add_announcement': 'Publier une annonce',
      'no_orders': 'Aucune commande.',
      'no_products': 'Aucun produit.',
      'no_categories': 'Aucune catégorie.',
      'no_customers': 'Aucun client enregistré.',
      'no_announcements': 'Aucune annonce.',
    }
  };

  /// Metin çeviri fonksiyonu
  static String tr(String key) {
    final lang = currentLanguage;
    if (_localizedValues.containsKey(lang) && _localizedValues[lang]!.containsKey(key)) {
      return _localizedValues[lang]![key]!;
    }
    // İngilizceye bak
    if (_localizedValues['en'] != null && _localizedValues['en']!.containsKey(key)) {
      return _localizedValues['en']![key]!;
    }
    // Türkçeye bak
    if (_localizedValues['tr'] != null && _localizedValues['tr']!.containsKey(key)) {
      return _localizedValues['tr']![key]!;
    }
    return key;
  }
}

/// Kolay kullanım için String extension
extension StringLocaleExtension on String {
  String get tr => AppLocale.tr(this);
}
